### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Develob** [arnog/mathlive#1093]
1. Is there an option for the virtual keyboard "alwaysOnDisplay" or something like that? So that the keyboard does not close when clicked outside the area.

2. Is there a latex property for line wrapping? I found the following command: 
\begin{multline}
    first part of the equation \\
    = second part of the equation
\end{multline}), 
but it looks cumbersome.

3. Can I completely change the keyboard structure? By adding a variety of their own styles.

**Comment by arnog** [comment]
1/ Four modes are available for the display of the virtual keyboard and can be controlled with the `virtualKeyboardMode` property:
- `manual`: pressing the virtual keyboard toggle button will show or hide the virtual keyboard. If hidden, the virtual keyboard is not shown when the field is focused until the toggle button is pressed.
- `onfocus: the virtual keyboard will be displayed whenever the field is focused and hidden when the field loses focus. In that case, the virtual keyboard toggle button is not displayed.
- `off: the virtual keyboard toggle button is not displayed, and the virtual keyboard is never triggered.
- `auto`: `onfocus` on touch-capable devices and 'off' otherwise (default).

2/ The `multline` environment is typically used for multi-line equations

3/ Sure. There is some information regarding customization of virtual keyboards here: https://cortexjs.io/mathlive/guides/virtual-keyboards/ In addition to what is described in this guide, the content of the virtual keyboard can be specified using HTML/CSS.

**Comment by Develob** [comment]
1. I've tried these modes, but they all don't fit, I need the keyboard to always be open, regardless of clicks outside the area.

2. And is there a property for line wrapping outside the context of multi-line levels?

3. Is there an extended document on how to customize the keyboard?
I try to do this, but it doesn't work.

'high-school-layer': {
    styles: 'backdrop',
    rows: [...]
}

сss file
  .backdrop {
    color:red;
}

**Comment by Develob** [comment]
> 1/ Four modes are available for the display of the virtual keyboard and can be controlled with the `virtualKeyboardMode` property:
> 
> * `manual`: pressing the virtual keyboard toggle button will show or hide the virtual keyboard. If hidden, the virtual keyboard is not shown when the field is focused until the toggle button is pressed.
> * `onfocus: the virtual keyboard will be displayed whenever the field is focused and hidden when the field loses focus. In that case, the virtual keyboard toggle button is not displayed.
> * `off: the virtual keyboard toggle button is not displayed, and the virtual keyboard is never triggered.
> * `auto`: `onfocus` on touch-capable devices and 'off' otherwise (default).
> 
> 2/ The `multline` environment is typically used for multi-line equations
> 
> 3/ Sure. There is some information regarding customization of virtual keyboards here: https://cortexjs.io/mathlive/guides/virtual-keyboards/ In addition to what is described in this guide, the content of the virtual keyboard can be specified using HTML/CSS.

1/ I've tried these modes, but they all don't fit, I need the keyboard to always be open, regardless of clicks outside the area.

2/ And is there a property for line wrapping outside the context of multi-line levels?

3/ Is there an extended document on how to customize the keyboard?
I try to do this, but it doesn't work.

'high-school-layer': {
styles: 'backdrop',
rows: [...]
}

сss file
.backdrop {
color:red;
}

4/ Is it possible to assign switching of all keyboards to the space bar?

**Comment by arnog** [comment]
1/ Use `makeSharedVirtualKeyboard()`, set the `virtualKeyboardMode` to `"off"`, and manually show/hide the keyboard.
2/ No
3/ There is an example here: https://github.com/arnog/mathlive/tree/master/examples/custom-virtual-keyboard
4/ Yes, using the `onKeystroke` handler.
