### ISSUE TITLE
[Capabilities question] Any way to enter multiple lines of equations?

### ISSUE THREAD

**Issue by jpskycak** [arnog/mathlive#113]
Is there a way to enter multiple lines of equations?

Example: displaying the lines

x+1=2
x=1

as separate lines in a single editor

**Comment by NSoiffer** [comment]
There's not an easy way, but you can type
```
\begin{multline}x+1=2 \\ x=1\end{multline}
```
You can also use `align`, `aligned`, and `split` instead of `multline`. I don't see any difference between the first two in mathlive. By default, they align the `=`, but you can use `&` as an alignment point. For example, the following aligns the `-` and `=`.
```
\begin{align}2x&-1&=2 \\ x&-22&=1\end{align}
```
It looks like there is a mathlive bug that pushes the `=` too far to the right:
![image](https://user-images.githubusercontent.com/1545836/46646276-402e7f00-cb3e-11e8-8d38-651242b9dcc1.png)

**Comment by jpskycak** [comment]
Thanks for the response! Looks like that does technically work, but I'm also looking for a solution that will make it render like normal as you're typing the lines (this solution only renders after the \end{multline}).

Maybe I'll try setting up a system where each line gets its own editor -- each time you press enter within an editor, it spawns a totally new editor directly underneath, and each time you clear out an editor, it deletes the editor.
