### ISSUE TITLE
Android WebView : Question

### ISSUE THREAD

**Issue by sk000007** [arnog/mathlive#1215]
Does MathLive work on Android WebView ?

**Comment by sk000007** [comment]
Thank you. It doesn't seem to work on emulator but working when deployed to real device.  
But the keyboard looks small and i guess can be controlled by CSS. Will try .
 Thank you again.

**Comment by arnog** [comment]
It looks like there's something wrong with the setup of the webview. Aside from the keyboard, you'll notice that the keyboard toggle icon is also very small. It would appear the zoom level on the document is off. You might want to try to remove calls to `setUseWideViewPort()` and `setInitialScale()` (even if using the default value of 0) and calling `setLoadWithOverviewMode(false)`

**Comment by arnog** [comment]
1/ There are several CSS variables you can use, including `--keycap-font-size` (note it's `--keycap-font-size` note `--keyboard-font-size`). See the Customizing the Appearance of the Virtual Keyboard Keycaps section in https://cortexjs.io/mathlive/guides/virtual-keyboards/. You can also use `--keyboard-height` and `--keycap-height` to further control the size of the keyboard.

2/ You can completely customize the layout of the keyboard. See Defining Custom Virtual Keyboards in https://cortexjs.io/mathlive/guides/virtual-keyboards/

3/ The virtual keyboard is indeed not navigable with screen readers. This is based on the feedback of users that use screen readers: rather than being able to navigate the virtual keyboard they preferred to directly type a Latex command using the BACKSLASH `\`  key, for example `\alpha`.

**Comment by sk000007** [comment]
@arnog Thank you for that..Yes, we will have some issues with full fledged 'accessibility' ..no harm done..but great job i say..will explore the customization part as you suggested further...but for a 'abled' person it will like like a charm. Will be in touch. Hope you dont mind.

**Comment by arnog** [comment]
For accessibility issues, I would recommend to get input from users who do require the use of screen readers and other assistive technology. It can be difficult for someone who doesn't use assistive technology (that's a better description than an 'abled' person) to envision what would actually be helpful. 

MathLive accessibility support has been built based on feedback of users using accessibility technology such as screen readers and braille readers and it has been successfully used to build software targeting specifically those users.

If you receive feedback from users that use assistive technology on how to improve the accessibility support in MathLive, I'd be very much interested in that input.

**Comment by sk000007** [comment]
Yes, thats an idea..use a normal input(accessibility enabled) and use MathLive for the rendering/presentation!!!! sort of dynamically switching the input mode!!!

As my experiments go deeper I will be working with people who use various assistive technologies and will surely pass on  the feedbacks to you.
