### ISSUE TITLE
Hi, I want to use mathlive for my project, but couldn't add it to my angular project (angular 12). Please help me adding it to the project

### ISSUE THREAD

**Issue by abinaya92s** [arnog/mathlive#1253]
## Description

[Describe the bug or feature]

[Include screenshots, screen recordings, code fragments or CodePen. If you get
an error message, include the text of the error message, not a screen capture of
it.]

[If you use Vue, React or some other framework, include a link to a minimal
project demonstrating the issue.]

[To quickly build a demo project, consider

- (https://github.com/mindreframer/mathlive-bug-issue-templates)
- (https://github.com/mindreframer/mathlive-create-app) ]

## Steps to Reproduce

[Provide steps that are specific and repeatable]

1. [First Step]
2. [Second Step]
3. [And so on...]

### Actual Behavior

[What happens when you follow the steps above?]

[If there are any error messages, include the exact text shown. Some error
messages may be displayed in the Javascript console. Copy and paste them. Do not
include a screenshot of the error messages.]

### Expected Behavior

[What did you expect to happen insteead?]

[Is this a regression: did it use to work in a previous version?]

### Environment

**MathLive version**

**Operating System** [macOS, Windows, iOS. Include the version]

**Browser** [Safari, Chrome, IE, Firefox, etc... Try several browsers and note
if there are differences between browsers. Include the version number of the
browsers.]

**Comment by arnog** [comment]
You may encounter problems if using different versions of Typescript in the project.

You can solve this by either:

- upgrading your Angular and Typescript version
- OR adding MathLive using a CDN by adding this line in your `index.html` file: `<script src="https://unpkg.com/mathlive/dist/mathlive.min.js"></script>`

**Comment by abinaya92s** [comment]
Hi Arnog, thanks for replying. sorry for being so vague.

This is my Angular versions

![Screen Shot 2021-11-28 at 10 09 50 AM](https://user-images.githubusercontent.com/95161574/143773931-cf104d9e-0839-47ed-b5f3-f6f016bc67ba.png)

I have included mathlive.js, mathlive.min.js from node_modules in angular.json file.

I am also getting the following console error

![Screen Shot 2021-11-28 at 11 28 50 AM](https://user-images.githubusercontent.com/95161574/143777072-53a2fda5-c9f6-4f63-b7c4-9f42474781e9.png)

Please help me use Mathlive virtual keyboard

**Comment by abinaya92s** [comment]
> Hi Arnog, thanks for replying. sorry for being so vague.
> 
> This is my Angular versions
> 
> ![Screen Shot 2021-11-28 at 10 09 50 AM](https://user-images.githubusercontent.com/95161574/143773931-cf104d9e-0839-47ed-b5f3-f6f016bc67ba.png)
> 
> I have included mathlive.js, mathlive.min.js from node_modules in angular.json file.
> 
> I am also getting the following console error
> 
> ![Screen Shot 2021-11-28 at 11 28 50 AM](https://user-images.githubusercontent.com/95161574/143777072-53a2fda5-c9f6-4f63-b7c4-9f42474781e9.png)
> 
> Please help me use Mathlive virtual keyboard

@arnog

**Comment by arnog** [comment]
I have a few suggestions:

- When you want to respond or add some information to an already open issue, there is no need to open a new issue (#1254). You can simply comment on the existing issue, including asking that the issue be reopened, if necessary.
- Avoid filing duplicate issues. In particular, it seems that this issue is substantially similar to #1218. In general, before open a new issue, it is good etiquette to search the existing open issues to see if there is already one open.
- When opening a new issue a template is provided for you to fill out. This is your chance to provide as much information as possible to make resolving the issue easier, in particular indicating clear steps to reproduce. In your case this would include making available a project that can demonstrate the problem you are running into. Without this information, it is very difficult to resolve issues.
- Luckily, in this case, since this is an already reported issue, you already have suggested solution to try out. I have repeated them above. Did you try the first or second one?

**Comment by abinaya92s** [comment]
Thanks for the suggestions Arno. 

Sorry for creating a new issue. I misunderstood that I need to open a new one, because the old one is closed. Thanks for the clarity.

I did check and tried the old link (#1218) I found another issue as well, however it didn't help me. 

I was still running into the issue. I'm pretty new to angular.

Solution 1:
  I am using the latest angular and typescript versions, so it didn't help resolve the issue.

Solution2:
 I tried using <script src="https://unpkg.com/mathlive/dist/mathlive.min.js"></script> in the index.html file. it didn't help either and am not sure what I am doing wrong. 

While using <script> tag within index.html, the project doesn't recognize the other "scripts" in the angular.json file.

<img width="840" alt="Screen Shot 2021-11-28 at 2 09 54 PM" src="https://user-images.githubusercontent.com/95161574/143782408-5d7de606-48ed-4620-92ea-54f9b016f0c6.png">

So i tried using 'mathlive.min.js from node_modules in angular.json file.

and getting the following error in console.

![Screen Shot 2021-11-28 at 11 28 50 AM](https://user-images.githubusercontent.com/95161574/143782484-76094058-5b4b-4827-b741-da604dedbae2.png)

I tried the solution once again now, just to be sure. now am getting the following error.

![Screen Shot 2021-11-28 at 2 18 35 PM](https://user-images.githubusercontent.com/95161574/143782657-25efbe2b-38c6-49ef-9e6d-c5738a6f35f4.png)

Thanks for the response and your time. Please let me know if you need any more information

**Comment by abinaya92s** [comment]
Sorry I ain't sure if I conveyed correctly. My aim is to use Virtual keyboard from mathlive in my angular 12 project for an application.

**Comment by arnog** [comment]
A few more comments:
- Regarding solution 1, my understanding is that there are multiple incompatible versions of Typescript being pulled in. However, I am not an expert in Angular, so I can't really provide more info than that. You may want to reach out to an Angular support forum.
- Note that if you proceed with Solution 1, you don't need `mathlive.js` if you already include `mathlive.min.js`: `mathlive.min.js` is the minimized version of `mathlive.js`, and therefore including both is redundant.
- If you proceed with Solution 2, you need to remove the references to mathlive in your `scripts` and `styles` property: if you include mathlive via a CDN you don't need to include it via your web bundler.

Since I still don't have access to your project and I am not an Angular expert, I'm afraid this is as far as I can help.

**Comment by abinaya92s** [comment]
Thanks you for the valuable comments Arno, will try to figure out solution 1. If couldn't find out that. Will try using mathlive via cdn removing all other mathlive packages and scripts.
