### ISSUE TITLE
click events inside of mathlive input not propagating out

### ISSUE THREAD

**Issue by strickinato** [arnog/mathlive#1439]
## Description

Click events that originate from inside text inside the mathfield element are getting swallowed, and do not propagate out of the element as I might expect.

See a reproduction of this here:
https://codepen.io/strickinato/pen/wvyaxZN

## Steps to Reproduce

1. Register a click event on the document
2. Click inside the math text inside of the math field
3. You will not see the event fire.

### Environment

**MathLive version**
Tested in mathlive 72.3 in chrome 100 on macos

**Comment by arnog** [comment]
Indeed.
Out of curiosity, what is the use case for this? That is, what do you expect to be able to do with the `click` event?

**Comment by arnog** [comment]
OK,  I think I know why it's not working, but I don't think it's fixable.

The `click` event is a "synthetic" event, it's not a "real" event. The "real" events are `mousedown`/`mouseup` and/or `pointerdown`/`pointerup`. The `click` event is generated by the browser when a pair of `mousedown`/`mouseup` (or `pointerdown`/`pointerup`) event occur within the  same DOM element. The spec for it is a bit wobbly, and browsers have wide latitude as to when to generate them or not (see https://www.w3.org/TR/pointerevents1/#compatibility-mapping-with-mouse-events). Safari on iOS in particular seems to only generate them for some  DOM elements, but not all.

Anyway, the problem here is that when clicking in the mathfield, in some (most) cases, the DOM tree that represents the formula is modified, specifically a DOM element to represent the caret is created, but the rest of the DOM elements representing the formula are "re-rendered". As a result, the DOM element on which the `mouseUp`/`pointerUp` event happens is different than the one on which the `mouseDown`/`pointerDown` occurred, and as a result, the browser decides to not generate a `click` event.

So, I'm not sure how I can fix this. On the other hand, there are numerous workarounds available, such as listening for a `pointerup` event instead, depending on what you are trying to accomplish (you could also listen for a `focus` event).

**Comment by strickinato** [comment]
> Out of curiosity, what is the use case for this?

Our mathlive component is hooked up to a hint that appears on the screen in some situations. There is a click handler on the application that dismisses the hint on click.

This came up, because when clicking inside the mathlive text, the hint was not being dismissed.

Appreciate the follow up, I think we'll be working around it by explicitly sending a "close hint" message on edit.

**Comment by arnog** [comment]
Ah, got it. Yeah that makes sense. Listening for `mousedown` might work as well. Although you probably want to listen to `keydown` too, for accessibility reasons.

**Comment by ChristopherChudzicki** [comment]
> Anyway, the problem here is that when clicking in the mathfield, in some (most) cases, the DOM tree that represents the formula is modified, specifically a DOM element to represent the caret is created, but the rest of the DOM elements representing the formula are "re-rendered". As a result, the DOM element on which the mouseUp/pointerUp event happens is different than the one on which the mouseDown/pointerDown occurred, and as a result, the browser decides to not generate a click event.

I want to add here, I think this issue is probably not that *"the DOM element on which the mouseUp/pointerUp event happens is different than the one on which the mouseDown/pointerDown occurred"*  but rather that the old DOM elements are removed.

Usually, when `pointerdown` and `pointerup` happen on different DOM elements, they share a common ancestor. But if the elements on which `pointerdown` occurred are being removed, then they won't have a common ancestor.

@arnog One possible approach might be setting elements to `display: none` on the `pointerdown`, then removing them ...subsequently (very minimal example: https://codesandbox.io/s/unruffled-galois-fhpm5w?file=/index.html ). This feels like a problem that must have a better solution, though 🤷 

It would be great if MathLive could support clicks on text... As you mention, there are workarounds with using other events besides click, but supporting standard click behavior makes integrating with external libraries easier. (In particular, integrating with any libraries that offer some sort of "Detect click outside of X" functionality).

**Comment by arnog** [comment]
@ChristopherChudzicki yes, you are correct regarding the common ancestor.

I can think of a way to generate a click event on the mathfield. However, this would be an event for the mathfield only, not any of its subcomponents, similar to the common ancestor behavior. That is, if you click on the keyboard toggle button in the mathfield, for example, you would get a `click` event on the mathfield. I suppose it's similar to a click on a textarea or a select input element whose sub-elements are not addressable (i.e. they behave as if their sub-elements are not in the DOM). If that's something that would be useful, I can look into adding it.

Keep in mind however that relying on a `click` event in general may not be what you want. Browsers are usually in control of which elements can generate `click` event. Safari on iOS for example as a very short list of elements that can generate `click` events. `div` for example cannot. So for a "detect click outside of X" functionality, this will have some severe limitation.

As a general rule, the better way to detect "click outside of X" is to insert in the DOM an invisible element covering the entire viewport, then "X" on top, and capture the pointer events with the invisible element.

**Comment by ChristopherChudzicki** [comment]
> As a general rule, the better way to detect "click outside of X" is to insert in the DOM an invisible element covering the entire viewport, then "X" on top, and capture the pointer events with the invisible element.

Unless I'm misunderstanding, that has some significant downsides like (a) interfering with scrolling and (b) requiring two clicks (or taps) to focus a different element.

> Safari on iOS for example ... 

MDN, at least, considers that a bug: https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event#safari_mobile

I do think there would be value in this feature: It seems to me that if (the text portion of) MathFields were to emit click events similar to traditional text inputs, integrating with external libraries would generally be easier. "Click away" behavior is the only concrete example I have at the moment, but if I come across more, I'll add them. And in terms of external libraries, Ant Design and Material UI both offer click-based dismissal, so it does seem reasonably common.

I completely understand if this is a no-go, I just wanted to make a small case for revisiting whether this really is a "Fact of life". MathLive is wonderful and there are certainly workarounds to deal with this issue.

**Comment by arnog** [comment]
OK, I think I've found a way to make it work. Change checked in the main branch.
