### ISSUE TITLE
set --keyboard-zindex

### ISSUE THREAD

**Issue by ArtemTyzhnenko** [arnog/mathlive#1522]
Hi guys!

can someone help me, I am new in the mathlive and have already spent a few days finding a way to set the z-index for the virtual keyboard. I've found --keyboard-zindex variable, maybe are any legal ways to modify it? 

Thank you very much in advance, and sorry if my question is stupid!

<img width="1189" alt="Screenshot 2022-06-30 at 14 37 31" src="https://user-images.githubusercontent.com/27298808/176668252-64dec19b-7063-4e90-b150-5c4685580a57.png">

**Comment by arnog** [comment]
Hi Artem. There's no stupid question!

We're going to try to figure out what's going on, but it looks like you're on the right track. The `--keyboard-zindex` CSS variable is indeed the one you can use to set the z-index of the virtual keyboard.

1/ What DOM element did you set the `--keyboard-zindex` on? It should be a parent element of the keyboard, i.e. typically the `<body>` tag.
2/ The default value of the `--keyboard-zindex` is 105. What did you set it at? What is the z-index of the modal panel you are trying to float on top of?
3/ Did you check the DOM  to make sure the modal panel was in the regular document DOM (and not in an i-frame)?
4/ Also while inspecting the DOM, what is the effective z-index of the keyboard?

Also, FYI, when reporting an issue it helps if you follow the issue template and provide as much information as possible (i.e. share the code you used, provide reproducible steps, etc...). And if you have questions about using a project, it is often more expedient to ask questions in an interactive forum rather than filing an issue report, which can take a while to get triaged (and the less information in the issue report, the longer it takes for it to be triaged). In the case of MathLive, that's a Gitter forum: https://gitter.im/cortex-js/community

**Comment by ArtemTyzhnenko** [comment]
Hi Arno!
Thank you very much for the fast response!!
1.When I had found a description of --keyboard-zindex, I had't understood how and where I must set this value :(
I've just tried to set it as an attribute on the body 
but got an error : 
<img width="352" alt="Screenshot 2022-06-30 at 17 11 55" src="https://user-images.githubusercontent.com/27298808/176699504-2a5695a2-d90e-4a35-8b3b-7a7597647b05.png">

      document.body.setAttribute('--keyboard-zindex', '2000');
maybe you can provide some example how to do it correctly (maybe I missed something from doc :( )

2/ on my projects we use dialog modal from material-ui, it has z-index === 1300 as default. (we can change it, but in our case, we are creating a component library for a lot of our projects and we don't want to change the default values of material-ui)
3/yep, I've checked it and it mounts into the DOM
4/I can't check the z-index of the keyboard because can't find a method to make it always visible

sorry that I've opened the issue and thank you very much for the link to the community it will be very helpful  place for me :)

Thank you alot

**Comment by ArtemTyzhnenko** [comment]
oh my God, it works !!!
thank you very much, Arno!!!

here is the description of --keyboard-zindex https://cortexjs.io/docs/mathlive/#(MathfieldElement%3Aclass) , and yeah, I think it nowhere mentioned that we should to assigned style to the parent element (but of course, I can mistake :( )
<img width="701" alt="Screenshot 2022-06-30 at 19 30 28" src="https://user-images.githubusercontent.com/27298808/176730054-9ba018e0-cc32-439e-aee0-3a0190578a51.png">
