### ISSUE TITLE
Question: Is Mathlive keyboard accessible? 

### ISSUE THREAD

**Issue by nesh325** [arnog/mathlive#1577]
Was playing around with the demo editors but I couldn't figure out how to tab to the keyboard from the input. I looked in the documentation but couldn't find anything on it. 

Is there a place to view keys that can be used for tabbing from input to keyboard and back.  Also tabbing through the open virtual keyboard? 

Right now when I try tabbing inside of the virtual keyboard it just closes it.

**Comment by arnog** [comment]
Yes, MathLive is keyboard accessible. 

If you have a physical keyboard you can use it to interact with the mathfield to enter any formula you desire, including raw LaTeX if necessary (by pressing the `\` or `ESC` key). You can do other operations such as selecting using various keyboard shortcuts: https://cortexjs.io/mathlive/reference/keybindings/

If you do not have a physical keyboard, you can use the virtual keyboard instead. The virtual keyboard itself is not keyboard navigable, since that would require to have a physical keyboard, in which case you can use the physical keyboard for input. Similarly, the virtual keyboard on iOS and Android are not keyboard navigable.

**Comment by nesh325** [comment]
Thanks for the quick reply!  I was hoping the virtual keyboard would be accessible with just the keyboard an no mouse as well. Is there any way around this with a custom solution on my end?

**Comment by arnog** [comment]
It might be possible. I haven't tested it myself, so I can't be 100% confident. I can think of two paths:
- you can customize the virtual keyboard and replace it with your own version as HTML markup with some special attributes. You might be able to make that markup keyboard focusable. You would probably need to take control of the virtual keyboard focusing, since the default behavior is for the virtual keyboard to get hidden when the mathfield loses focus). This can be done using a `virtualKeyboardMode` of `"off"`, and then showing/hiding the virtual keyboard programmatically (when the mathfield gains focus, for example).
- if the solution above does not work, MathLive could be modified so that the keyboard is made focusable and keyboard navigable. This would probably involve changing the markup generated for the keyboard so that the keycaps include a `tabindex` attribute, as well as the other UI elements of the keyboard (the tab to switch amongst keyboard, the undo buttons, etc...)

I'm curious as to what is your use case for this, though. If this is a use case with broad enough applicability, I'd be happy to revisit this issue in MathLive

**Comment by nesh325** [comment]
I'll have check out the first option, I haven't dived too much into the library just yet. I was working with MathQuill and found out about this library and love that it's well maintained, supports a lot of latex expressions and screen reader support. In MathQuill there's an option to make your own buttons which you can bind a write()/cmd() function that will insert the specified latex into the editor. Is this something that could also be another option? It would make it so someone can create their own custom keyboard and control the accessibility that way as well. 

I work at a non profit company that creates interactive online courses for students from grades 1-12. Our courses are funded by the government and used by students across the country. The math editor would be used mainly by course creators to help generate math equations for courses. My company follows a pretty strict accessibility requirement, so we make sure we try and cover all cases.

**Comment by arnog** [comment]
Yes, you can have your own UI elements/buttons control the mathfield. You would use `mf.insert()` for example to insert LaTeX into the mathfield, or `mf.executeCommand()` to control the cursor, etc... See https://cortexjs.io/mathlive/guides/commands/ for a list of available commands.

That said, I believe MathLive out-of-the-box is section 508 compliant. It has been developed with feedback from screen reader users, it includes support for text-to-speech output and navigation and braille readers, and it has been used by Benetech (https://github.com/benetech/MathShare) for a project that was specifically aimed to be inclusive of users with low and no vision, and that was funded in part by the US Dept of Education.

**Comment by nesh325** [comment]
Sorry, I didn't look too closely at the library to notice that that was possible. That's perfect, thanks a for pointing that out! I'll play around with it and see if I can get the desired outcome. 

Really good to know that it has been used specifically for accessibility. I guess in Canada our accessibility requirement for keyboard only usage is really strict. 

Thanks for the help and the information on the accessibility of the library. This helped me make up my mind now to go with MathLive instead of MathQuill
