### ISSUE TITLE
Feature: "fill in the blank"

### ISSUE THREAD

**Issue by arnog** [arnog/mathlive#163]
In educational environments, it is common to present students with a partially filled answer with some portions missing that they need to fill in:

<img width="108" alt="" src="https://user-images.githubusercontent.com/760798/55516032-0045e180-5621-11e9-8cc2-fde233b60724.png">

This "fill in the blank" feature would allow the creation of a mathfield in "readonly" mode, that is the mathfield would behave as if it was a static element, except for some areas inside it that would be editable. Those areas would be indicated by a specific latex command, such as `\placeholder`.

Furthermore, it should be possible to read (or modify) the content of these areas programmatically and be notified when these areas are modified. To facilitate this, an identifier could get associated with each placeholder.

Example of what this could look like:

```html
    <div id='mf'>\frac{8}{\placeholder[answer]{}}=2</div>
```

```javascript
    MathLive.makeMathField('mf', {
        readOnly: true,
        onPlaceholderDidChange: (mf, id) => {
            console.log('The answer is ', mf.$getPlaceholderContent(id));
        }
    });
```

**Comment by jlchereau** [comment]
Make sure you can edit the template with MathLive. MathQuill as such placeholders but you cannot use MathQuill to edit a formula that has such placeholders.

**Comment by arnog** [comment]
Thanks for the feedback! I want to make sure I get it right, though. Do you mean that the "template" (i.e. the part of the formula that is outside the placeholder) should be user editable as well? Can you provide more details on the use case you are thinking about?

**Comment by jlchereau** [comment]
I am currently building (still beta, not yet v1) an environment to build exercises, that is the equivalent of http://khan.github.io/perseus/.

![image](https://user-images.githubusercontent.com/2556751/57980822-04d72580-7a28-11e9-9ce8-337e3e84d657.png)

The general idea is PowerPoint slides that have the ability to ask questions, record user answers and compute a score.

I am currently using matquill/KaTeX to enter and display formulas but I am considering switching to mathlive (currently experimenting, not yet decided).

As you can realize we have a design mode and a play mode, like PowerPoint. SO any feature needs to be supported in both environments including a \placeholder feature.

**Comment by arnog** [comment]
Ah, OK, got it. That's good input, as this was not a use case I had considered, but it makes sense.

**Comment by NSoiffer** [comment]
I think `\placeholder` should take three arguments:
1. Initial contents so that you can have something besides an empty box. E.g., you want`___` or `unit` as initial values (these should act like the placeholder for an `input` element)
2. An id so it is easy to find the placeholder programmatically (as you showed)
3. The contents of the placeholder

Also, I know that your `onPlaceholderDidChange` example was just an example, but often multiple characters are needed in the answer. So maybe a better example is when the placeholder loses the focus. More likely, someone would have a "ok" or "done" button.

**Comment by dangcuuson** [comment]
Just want to share my current "workaround" for this feature:
1. Render static math (with \placeholder)
2. Find all span with `.ML__placeholder` class
3. Call `makeMathField` on each of those spans

![image](https://user-images.githubusercontent.com/20551609/61384617-513dc500-a8f4-11e9-8fab-62dda9dcd61b.png)

It works great. Only drawback is the layout won't look correct if I type another fraction in those boxes (obviously because it's not aware that it's already in another fraction). But it's fine to me since my use cases don't need to deal with nested fractions.

**Comment by caleb-flores** [comment]
Is there any plan to include this feature in the near future?

**Comment by arnog** [comment]
@caleb-flores it is not actively worked on at the moment. If anyone is interested to work on this and submit a PR, let me know.

**Comment by caleb-flores** [comment]
@arnog I am interested to work on this and submit the PR.

**Comment by arnog** [comment]
@caleb-flores Awesome! Let me know if you have any questions or if you want to chat about it in the gitter room (https://gitter.im/cortex-js/community)

**Comment by arnog** [comment]
This feature was in PR#1138. Closing.
