### ISSUE TITLE
German keyboard still not working from unpkg

### ISSUE THREAD

**Issue by ingodahn** [arnog/mathlive#174]
The attached file, adapted from a one of the standard examples and loading mathlive by
`import MathLive from 'https://unpkg.com/mathlive/dist/mathlive.mjs';`
does not work with a German keyboard.

[index.esm.html.zip](https://github.com/arnog/mathlive/files/3092218/index.esm.html.zip)

**Comment by arnog** [comment]
The package on unpkg.com is the latest release. The latest release (0.27.4) does not include the fix for the German keyboard. You can view what is included (or not) in the release on the releases page https://github.com/arnog/mathlive/releases and clicking on the "n commits to master since this release" link.
