### ISSUE TITLE
Chained Exponents Collapse on Division

### ISSUE THREAD

**Issue by MatousAc** [arnog/mathlive#1817]
In a math-field, you can "chain exponents" using input such as `2^1^3`. When you select this input and press `/` to divide, the chained exponents collapse into a single number such as `2^{13}`.

[Here's a link to the Codepen displaying the issue below.](https://codepen.io/MatousAc/pen/RwBmYBV)
![chainedExponentsBug](https://user-images.githubusercontent.com/56884762/217624367-722ce83c-7381-407b-ae42-38d7673482ce.gif)

## Steps to Reproduce

1. Click on math-field
2. Type something with chained exponents like: `2^1^3`
3. Select what you have typed and press `/` to divide.

### Actual Behavior
Exponents just become one number.

### Expected Behavior
No change to the exponents.

### Environment
**MathLive version**: 0.87.1
**Operating System**: Windows 11
**Browser** Chrome Version 110.0.5481.78 (Official Build) (64-bit), Edge Version 109.0.1518.78 (Official build) (64-bit)
No difference between browsers.

**Comment by arnog** [comment]
This works now, sort of. There is a caveat... In LaTeX, `x^1^2` is actually invalid. You need to use braces, i.e. `x^{1^2}` (see https://tex.stackexchange.com/questions/295828/double-powers-does-not-work).

Editing in MathLive works now because the serializer will automatically include the braces when necessary. However, if you enter `x^2^3` in LaTeX mode, it will be interpreted as `x^{23}` (note that LaTeX just gives an error in this case).
