### ISSUE TITLE
[bug] Move-out event not called when caret in a matrix

### ISSUE THREAD

**Issue by ichibha** [arnog/mathlive#1842]
I found something like a bug.
When the caret is at the bottom of a matrix like 
![スクリーンショット 2023-02-20 13 47 09](https://user-images.githubusercontent.com/41054969/220011892-b0c177dc-b7a1-4156-8fc7-9b03612f8ef1.png)
typing "ArrowDown" does not call the "move-out" event although the caret does not move. 
I use "mathlive": "^0.86.0" and MacOS 13.2.1（22D68）.

**Comment by ichibha** [comment]
As another similar issue, when the caret is at the superscript like 
![スクリーンショット 2023-02-20 14 01 56](https://user-images.githubusercontent.com/41054969/220013744-7d06cab7-9d43-4233-a33b-9bb1efa786e9.png)
typing "ArrowDown" may be expected to move the cursor to the subscript. 
However, this actually does not move the cursor and calls the move-out event.

**Comment by WildYellowfin** [comment]
I'm not 100% sure this is a bug, since this is very explicit behavior in the model. See [here](https://github.com/arnog/mathlive/blob/857a09921a7ca62bf0e2ec8c7525804103fc83e0/src/editor-model/commands.ts#L482) and [here](https://github.com/arnog/mathlive/blob/857a09921a7ca62bf0e2ec8c7525804103fc83e0/src/editor-model/commands.ts#L536).

**Comment by ichibha** [comment]
@WildYellowfin Thank you for your answer. 
This is a specification of code rather than a bug as you said.
I will fix my program to realize my aiming behavior.

**Comment by arnog** [comment]
Reopening. That behavior is incorrect.
