### ISSUE TITLE
[Question] Movement of caret across \vec

### ISSUE THREAD

**Issue by ichibha** [arnog/mathlive#1860]
Hi, 

I have a question. 

With mathlive version 0.89.4, the caret moves around \vec with moveToPreviousChar and moveToNextChar like
%----------------------------------------
left to right: |a\vec{b}c -> a|\vec{b}c -> a\vec{b}|c -> a\vec{b}c|
right to left: a\vec{b}c| -> a\vec{b|}c -> a|\vec{b}c -> |a\vec{b}c

(The value of math-field is a\vec{b}c and | is the caret.)
%----------------------------------------

Why does the caret not move one-by-one?: 
%----------------------------------------
both direction: |a\vec{b}c <-> a|\vec{b}c <-> a\vec{|b}c <-> a\vec{b|}c <-> a\vec{b}|c <-> a\vec{b}c|
%----------------------------------------

I am interested in if this is the expected behavior or will be revised.

**Comment by arnog** [comment]
This is the expected behavior.

Keep in mind that the internal representation of the expression does not match directly to the LaTeX while editing. So, `\vec{b}` is represented internally as `an atom of type vector, with a content of "b"`. When navigating over this particular kind of atom (a vector atom), the entire atom is considered, and not its "content".

However, this comes down to a UI decision. It seems that in most cases handling vector atoms as a unit is more useful, and that editing the "content" of a vector is something that one would want more rarely.

**Comment by ichibha** [comment]
@arnog Thank you for your kind answer. 

> It seems that in most cases handling vector atoms as a unit is more useful, and that editing the "content" of a vector is something that one would want more rarely.

I agree with you. Then, in the following case, is the whole of \vec b better be deleted? 
For case that the value of math-field is "a\vec bc" and the caret is at the right edge, typing ArrowLeft and Backspace deletes "b" and remains the vector without any content.
Or, is this to provide a method to edit the content of a vector?

**Comment by ichibha** [comment]
@arnog Similarly, clicking the vector atom and typing a letter adds the letter in the vector atom's content. Should the letter be added next to the vector atom?

**Comment by arnog** [comment]
No, that's the same bug. Thanks for pointing it out.

I have checked in a fix.
