### ISSUE TITLE
Use operator precedence to determine argument of /, etc

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#189]
## Description
Arno and I have discussed this in the past, but I don't think I ever put into an issue. Now I have...

@saivan brought up the problem again in a comment in https://github.com/arnog/mathlive/issues/185#issuecomment-489025046:

> I'm not sure if I'm in the right place for this. But it seems like typing something like "sinx" followed by "/" should give you \frac{\sin{x}}{ _ }but currently, it gives you \sin \frac{x}{_}. I'd say that when you type "/", the expectation is that the previous term to the immediate left of your cursor will end up on the top of the fraction.
> 
> Similarly for parenthesis, an opening parenthesis somewhere, should put the closing parenthesis (by default), at the complete end of the same scope.

I think the proper thing to do is to use an operator's precedence in determining the argument to division and scripts and other 2D operators. The [MathML operator dictionary](https://www.w3.org/TR/MathML3/appendixc.html#oper-dict.entries-table) is a good place to find relative precedence along with whether an operator is prefix, infix, or postfix, or potentially more than one of those (with different relative precedence values). In the case of `sin x /` and similarly `sin(x) /`, the operator dictionary puts function application at 850 and `/` at 660. This means that `sin` binds more tightly to it's argument than does `/` so that `sin x` should be the numerator, not `x`. [I'm not sure why U+2044 (fraction slash) and U+2215 (division slash) are given 265; seems like a mistake]

In order to do the right thing, you really need to parse the expression because you might have something more complicated such as  `sin^-1 sin x /` which should have `sin^-1 sin x` as the numerator. I suspect that conversion to maston has to deal with this type of issue, so the functionality is at least partially in mathlive already. Years ago (actually now decades, sigh) I did that with the Mathematica frontend's editor and that seems to have been well accepted. On the other hand, most editors don't bother with this and I don't see many complaints, so maybe people just are accepting of what they have to use 😌

FYI: for scripted expressions, the precedence should come from the base of the script (recursively). Typically this might happen with sums and integrals. The above example with `sin ^ -1` doesn't apply here because the operator is function application, not the `sin`.

**Comment by saivan** [comment]
Oh awesome! This thanks for this :) To be honest, this was the main (and only) reason I don't use mathlive at https://treena.org/lesson/complex-grapher. My users just seemed to get very frustrated when it didn't work the way they expect. 

I now use guppy, but it seems that it is no longer maintained. But the general behaviour was more intuitive (most of the time) - except for the brackets :P

**Comment by arnog** [comment]
I'm very open to changing how the implicit numerator is determined when "/" is pressed, but it's not clear to me that using operator precedence is the right answer. MathLive does have a built-in operator precedence dictionary (`OP_PRECEDENCE ` in maston.js:268) which is used when determining the AST for the formula, so this *could* be used if necessary, but I'm not convinced.

It seems to me that the key question is what do users expect the numerator to be when they press that key. And a good proxy for that question is: what are the most common "expression template". Whichever is the most common should be used to determine the implicit numerator, with the assumption that minimizing the number of keystrokes to enter a formula is desirable. The other less common template will require additional keystrokes to select the desired numerator before pressing the "/" key in order to have the desired result.

It is possible that if all the potential templates are roughly equally probable, any solution picked will result in a minor inconvenience. If there are more significant differences in the distribution of the frequency of the templates and a lower frequency template is used, then user dissatisfaction will be greater and this should be avoided.

I don't have data for the frequency of the potential templates, but I would be very interested if anyone could help capture, perhaps by asking users of your application. A simple survey could be asking for some of the expressions below, assuming you are at the end of the expression and press the "/" key, what would you expect the numerator to be:
- `3 + 2 sin x`
- `3 + 2 sin (x)`
- `3 + 2 sin x + 1`
- `3 + x`
- `3 + 2x`

MathLive currently handles the first and second expressions in the same way, using "x" as the numerator, and it seems reasonable to say that the second one should be treated differently: if the user has made the effort to add the parenthesis, they are presumably significant, and if the cursor is *outside* the parentheses, the user presumably meant `2 sin (x)` as the numerator (or `3 + 2 sin (x)`?)

**Comment by saivan** [comment]
I'm coming from a teaching perspective here - but the most common way that students add divisions on scientific calculators is usually as an afterthought :P So to answer your question most directly - at least from my expectation, I'd have:

`3 + 2 sin x` > `3 + (2 sinx) / ( __ )`
`3 + 2 sin (x)` > `3 + (2 sin( x ) ) / ( __ )`
`3 + 2 sin x + 1` > `3 + 2 sin x + 1 / ( __ )`
`3 + x` > `3 + x/( __ )`
`3 + 2x` > `3 + ( 2x )/( __ )`

And if I may contribute some more:
`3 + 4(sin(x) ` > `3 + 4(sin(x))/( __ ) `
`3 + 4(sin(x) + 5x ` > `3 + 4(sin(x) + (5x)/(__) `

So the simple and possibly most sensible rule to follow is - look left until you hit either:

- The start of the expression ( beginning of a string, opening bracket, etc...)
- A term separator (a plus or a minus sign)

I feel like this is sensible behaviour, because reasonably, you'd type the expression out from left to right in reading order. It's also what every wysiwyg math editor I've ever used has done (try https://desmos.com)

**Comment by arnog** [comment]
Ok, that makes sense. 

Can you clarify your two last examples: did you leave a closing parent missing intentionally? And can you clarify what you expect the numerator to be by putting it in parens or perhaps using [] to disambiguate, i.e. "3 + [4(sin(x))]/[...]" or "3 + 4[(sin(x))]/[...]" or...

**Comment by saivan** [comment]
Yep of course

`3 + 4(sin(x) > 3 + 4[sin(x)]/[ __ ]`

So for this one when you type the ( to the left of sin, it would implicitly add a bracket to the end of the expression, but when you type /, we destroy the original bracket and make sin(x) the numerator.

A similar thing would happen here:

`3 + 4(sin(x) + 5x > 3 + 4(sin(x) + [5x]/[__]`

Since we press the forward slash after the 5x term, we would most likely expect the 5x to become the numerator. 

I can largely say that this is how you would read these expressions in english. For example, you'd say `three plus 4, open bracket, sin x plus five x over ...`. As a general rule, I'd expect to be able to type the expression in the way I'd read it, because that will avoid the need for me to back track when I realise that I forgot to type something.

**Comment by NSoiffer** [comment]
> So the simple and possibly most sensible rule to follow is - look left until you hit either:
> 
> * The start of the expression ( beginning of a string, opening bracket, etc...)
> * A term separator (a plus or a minus sign)

This rule is too simple. Relational operators would never be part of a numerator. E.g `x = a /` should not include the `=`. Similarly, there are lots of other operators that would not want to be in the numerator normally. Most likely anything with a precedence lower than times unless they are in parens or other bracketing operator.

I have extracted the math expressions some open source math textbooks. The textbooks range from pre-algrebra through calculus. They use MathML for the math. I think there were over 100,000 expressions among them, so that's lots of data. I can write some python code to get some statistics as to what is in the numerator of fractions and what precedes the numerator. The easy thing to do is write some regular expression patterns, but they will fail when there are nested fractions and likely some other cases. I suspect those are not that common, so those failures wouldn't skew the numbers much. I could use the XML parser to do it right, but then I'd need to write tree traversal code looking for the pattern and that's a bit more work.

Before I do anything, would these examples be useful? If so, what info really needs to be gathered and how should it be grouped/displayed to be useful?

**Comment by saivan** [comment]
Oh wow, that was fast :p
