### ISSUE TITLE
Fraction division line not correctly aligned in the middle

### ISSUE THREAD

**Issue by AlienKevin** [arnog/mathlive#191]
**Describe the bug**
Fraction division line not correctly aligned in the middle.

**To Reproduce**
Type in fractions in MathLive.

**Screenshots**
![fe6056eb-c2b0-4c0b-b201-d35743ff082f](https://user-images.githubusercontent.com/22850071/57192262-7aa5a200-6efc-11e9-8c74-4d0d83ab4871.gif)

**Environment**
- Device: PC
- OS: Windows 10
- Browser: 74.0.3729.131 (latest as of 5/5/2019)

**Comment by arnog** [comment]
I can't reproduce it. This problem could be cause by a problem loading the stylesheet. Can you verify that you have mathlive.css and mathlive.core.css loaded? If you can provide a URL that demonstrates this issue I can have a look.

**Comment by AlienKevin** [comment]
![4987310e-af74-40b3-99bd-f20956866377](https://user-images.githubusercontent.com/22850071/57198010-ff63e080-6f3b-11e9-9416-362725b2766a.gif)

Here's my code on codesandbox:
[![Edit m4k54z3roj](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m4k54z3roj?fontsize=14)

**Comment by arnog** [comment]
Awesome, thank you. I can reproduce it now.
The problem appears to be due to using Quirks mode. Not sure exactly which quirks is being triggered and if a workaround is possible, but in the meantime, you can avoid this by using the standard mode rather than the quirks mode. To do this, add `<!doctype html>` at the start of your document.

**Comment by AlienKevin** [comment]
Thanks, that solves my problem.
