### ISSUE TITLE
virtual keyboard hides when moving focus off mathfield with mathVirtualKeyboardPolicy="manual"

### ISSUE THREAD

**Issue by albertchae** [arnog/mathlive#1914]
## Description

Hi, I want to control visibility of the virtual keyboard manually (similar to described in this issue https://github.com/arnog/mathlive/issues/1345). I see that `virtualKeyboardMode` was recently renamed to `mathVirtualKeyboardPolicy`, but when I try setting this to `manual`, the keyboard still seems to hide when moving focus off the mathfield (it does prevent it from showing automatically when focusing on the mathfield though).

Here is a reproduction https://albertchae.github.io/mathlive-hide-when-focus-changed/. Source code is at https://github.com/albertchae/mathlive-hide-when-focus-changed. You'll see that when the page is loaded, the keyboard is shown, but if you click anywhere on the body, then the keyboard goes away. Is this intended behavior?

## Steps to Reproduce

1. Load https://albertchae.github.io/mathlive-hide-when-focus-changed/
2. In console, you can type `mathField.mathVirtualKeyboardPolicy` to verify it is set to `manual`
3. Click on the body (or the take focus button if tapping the body doesn't switch focus, like in iOS safari)

### Actual Behavior

The keyboard is hidden.

### Expected Behavior

The keyboard is not hidden, because we would control its visibility manually.

### Environment

**MathLive version** 0.90.11

I can reproduce this on iOS 16.3.1 with mobile safari and mobile chrome version 111.0.5563.101.

I also see this on macOS 13.2.1 with both Chrome 111.0.5563.146 and Firefox 111.0

### Recording with mobile chrome
https://user-images.githubusercontent.com/217050/229718798-104383ed-ed80-40bd-aef2-a02ef7cdf83c.MP4

### Recording with mobile safari
https://user-images.githubusercontent.com/217050/229718818-90517293-5a95-41ae-9d58-a041fc992811.MP4

**Comment by arnog** [comment]
That's an interesting issue. 

The current behavior is as intended. It reflects my interpretation of the W3C virtual keyboard spec, which is a work in progress but something I was trying to follow (https://www.w3.org/TR/virtual-keyboard/#dfn-manual). On re-reading the spec, it actually does not speak clearly regarding this situation.

Since `mathVirtualKeyboardPolicy` is a property of a mathfield, it would suggest that it dictates what happens when the mathfield is focused. However, when no mathfield is focused, my interpretation was that since the virtual keyboard did not apply it should be hidden.

I could see an argument that you would want the virtual keyboard to not be hidden if the policy that caused the keyboard to appear was `"manual"`.

Could you tell me more about your use case? Why do you want the virtual keyboard to still be visible even when no mathfield has focus? A potential downside of this is that the virtual keyboard could be visible, but interacting with it will do nothing since no mathfield can receive its input, which might be confusing to a user.

**Comment by albertchae** [comment]
Thank you for the explanation and it makes sense that having a visible virtual keyboard without a focused mathfield means there's nowhere for the input events to be sent to. Given that, I think what I'll try to do for now is to keep the mathfield from losing focus, although it may not always be possible for us.

Our use case is a game where you have to edit an equation and then trigger an animation. You can try a preview of the game here https://sinerider.hackclub.dev/ (currently using MathQuill as the input).

Since we wanted to support mobile as well, we were looking into replacing MathQuill with MathLive. You can see a preview deploy of this at https://sinerider-htdfkdckd.hackclub.dev/ (N.B. this sometimes crashes on iOS for reasons unrelated to MathLive, so trying on android is probably best). The draft PR for this is https://github.com/hackclub/sinerider/pull/320. 

MathLive has worked great from the standpoint of LaTeX input and a mobile friendly virtual keyboard, but we wanted to keep the keyboard always visible because resizing the game canvas on toggling the keyboard back and forth could cause some other issues. Right now I am listening for `insertLineBreak` (is this the best way to listen for the virtual enter key?) to start the game simulation, but for some reason in the game logic (not in MathLive), this is causing the mathfield to lose focus and thus hides the keyboard. However, even if we fix that, there are other interactive buttons on the screen that I believe would hide the keyboard due to focus moving, so I guess what could be ideal is that we keep the keyboard up even if the mathfield loses focus, but on interacting with the keyboard, we can configure a mathfield to return focus to so that the keyboard's input events go there.

**Comment by arnog** [comment]
OK, so first of all, this is freaking awesome. Love the concept and it looks great. Congrats.

Yes, listening to `insertLineBreak` is the best way to listen for the virtual/physical enter key.

I was thinking about adding an option to customize that key, so that you could choose its label (i.e. "continue" or "go" or a SVG icon). Is that something you'd find useful?

You have a compelling use case to always show the keyboard. I'm going to think about it a bit, either modifying the behavior of "manual" or adding a new policy...

BTW, I'm in the process of updating the virtual keyboard documentation, as the way to implement custom layouts has recently been significantly improved, in case that's something you'd be interested in.

**Comment by polytroper** [comment]
Hey @arnog, thank you for your quick response and your kind words! A customizable enter key would definitely be useful for us.

We are launching on April 14th. Would the persistent keyboard change be likely to go in before that? I'm not rushing you, just trying to decide if we want to shoot for beta mobile support 😅 

@albertchae, the equation loses focus when the simulation starts because the field gets disabled to prevent players from editing their solution while it is running

**Comment by arnog** [comment]
@polytroper yes, the change would be in before that.

**Comment by polytroper** [comment]
Ahhh thank you so much!! Really appreciate your help

**Comment by albertchae** [comment]
@arnog Thanks again for the quick response. I just incorporated your change and it works great, although now we have to figure out where to give focus so we can receive events.

> OK, so first of all, this is freaking awesome. Love the concept and it looks great. Congrats.

🎉 @polytroper and others at https://github.com/hackclub/ deserve the credit for the idea and the implementation

> Yes, listening to insertLineBreak is the best way to listen for the virtual/physical enter key.

Thanks. Let me know if I should open a separate issue for this, but one thing I'm seeing now is that I believe `insertLineBreak` is an `InputEvent`, [which only gets sent to `<input>`, `<select>` or `<textarea>` elements](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event), so I don't think I can listen for this event on `body` after the mathfield loses focus. Does the virtual keyboard spec specify anything about sending [`KeyboardEvent`s](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent)? Unless I missed something, it only talks about geometry and showing/hiding.

> BTW, I'm in the process of updating the virtual keyboard documentation, as the way to implement custom layouts has recently been significantly improved, in case that's something you'd be interested in.

Yes, I think custom layouts is something we'd probably want to explore later in addition to the customizable enter key label. I haven't finished some of the advanced levels in sinerider yet, but I imagine we'd want to limit the keyboard to only the inputs needed to finish the game.

**Comment by arnog** [comment]
I'm not sure I completely understand what you are trying to do, but the `insertLineBreak` would indeed only be emitted from the mathfield element. The keyboard itself doesn't emit keyboard events, so you would need to listen on the mathfield.

Re-reading this thread, it looks like you want to prevent the mathfield from being edited at some point. You can still have the mathfield focused if you set it to `readonly` (not `disabled`).

Also, I've added "mathVirtualKeyboard.actionKeycap` to customize the return/continue keycap.

**Comment by albertchae** [comment]
Ah got it, setting it to `readonly` but keeping focus is pretty clever so I'll try that. For context, I was trying to replicate the functionality of the `keyup` listener in https://github.com/hackclub/sinerider/commit/5153d4cb364b7c84e905cc94c2f6ae98b71844a4#diff-ba98b2d14b7d2c8892150124ac5b7743be06c04c68ecd8e72b3a6faef5dd3aadL269-L274.

I'll try out the return/continue keycap, thanks again!

**Comment by arnog** [comment]
Oh, I see. That's interesting. Right now when the virtual keyboard is not connected to a mathfield it doesn't dispatch any events... I could have it bubble up some `keyup` events, at least in some cases. For some keys it can get tricky as pressing some keys doesn't generate a single character, but a LaTeX expression... Could work for Return, though.
