### ISSUE TITLE
Can't paste in latex mode from firefox

### ISSUE THREAD

**Issue by WildYellowfin** [arnog/mathlive#1937]
`Uncaught TypeError: navigator.clipboard.readText is not a function`

Firefox does not expose `navigator.clipboard`, and tbh it's a bit annoying that Chrome asks for permission.

**Comment by arnog** [comment]
I believe this only happens when pressing the paste icon in the virtual keyboard, right?

Unfortunately, that seems to reflect the state of the art with regard to clipboard support in browsers. For some reason, interacting with the clipboard is viewed as a high security risk. So, unless the paste operation is initiated by the browser (via the Edit > Paste menu or by pressing `ctrl+V` in an editable context), the best you can do, AFAICT, is to beg the browser for clipboard access. In the case of Chrome (and Safari) that result in an permission dialog, and in the case of Firefox... there's just no way at the moment to do it, but according to MDN they're working on it.

**Comment by WildYellowfin** [comment]
This happens for me even with `ctrl+V`...

**Comment by mgreminger** [comment]
I'm taking a look at this since `Ctrl/Cmd+v` requiring browser permission is a blocker for me. I've identified the cause of the issue, triggering the paste command with `keydown` rather than a `paste` event. With the `paste` event, `navigator.clipboard` is not needed since the event object will have the clipboard data. I'm still working on a solution. Might have something to propose later today.

**Comment by arnog** [comment]
This should now work correctly.
