### ISSUE TITLE
v0.29 fails on Microsoft Edge

### ISSUE THREAD

**Issue by jlchereau** [arnog/mathlive#195]
**Describe the bug**
v0.29 fails on Microsoft Edge and Internet Explorer

**To Reproduce**
1. Open Microsoft Edge or IE
2.. Go to mathlive.io
3. Cannot even focus on field to type
4. Example drop down does not work either

**Expected behavior**
Should at least work on Microsoft Edge

**Screenshots**

![image](https://user-images.githubusercontent.com/2556751/57966792-a8540780-794e-11e9-863d-297c50fb3364.png)

**Environment**
- Device: PC
- OS: Window 10
 - Browser edge
 - Version v0.29

**Comment by arnog** [comment]
I've looked into this issue which turned out to be extremely time consuming. 

Edge indeed fails to load MathLive. It does so silently: there are no error messages in the console, the module loading just fails. Switching to the non-module version does not help. After commenting lines of code after lines of code to find out which one failed, it turned out that the issue is that ChakraCore (Microsoft's JavaScript engine) does not support the spread operator: https://github.com/microsoft/ChakraCore/issues/3406 

Given that Microsoft has abandoned support for ChakraCore, this is unlikely to ever get fixed, until Microsoft completes switching over to Chromium.

I can see two options:

1/ transpile MathLive using Babel to polyfill the spread operator (and whatever else ChakraCore might not support or support poorly).

2/ drop support for Edge for now (Edge has a 4.5% browser marketshare right now, below that of IE at 9.5% and IE is already not supported). Note that the Chromium based-Edge, which is available as a preview here: https://www.microsoftedgeinsider.com/en-us/ does work correctly.

If supporting the current version of Edge is important for your application, I suggest that you consider option (1).

**Comment by jlchereau** [comment]
I am doing option 1 already and get:

![image](https://user-images.githubusercontent.com/2556751/57980339-65636400-7a22-11e9-9a9e-4e9486b3fa7a.png)

**Comment by arnog** [comment]
I am more than willing to consider better support for IE and Edge if someone were willing to financially support the cost of implementing it.
In the meantime I have added the workaround for the Unicode regex to include both Edge and Firefox.
