### ISSUE TITLE
Typing slowly yields different results

### ISSUE THREAD

**Issue by jlchereau** [arnog/mathlive#198]
**Describe the bug**
Typing slowly yields different results
Making corrections too.

**To Reproduce**
1. Go to mathlive.io
2. Type sum or \sum but wait a couple of seconds after the s
3. You do not get a sum sign

![image](https://user-images.githubusercontent.com/2556751/57981216-e3c50380-7a2c-11e9-91f6-55f5a9efa38a.png)

Alternatively:
1. Go to mathlve.io
2. Type sun or \sun (yes, a mistake) and correct the n into an m
3. You do not get a sum sign

**Expected behavior**
Typing pace or corrections should not affect result

**Environment**
- Device: PC
- OS: Windows
 - Browser Chrome
 - Version v0.29.0

**Comment by arnog** [comment]
The first issue is intentional and specific to mathlive.io: if you pause for a few seconds, the formula is evaluated and this interrupts the inline shortcut recognition. You can verify this by using https://mathlive.io/deploy/examples/basic/index.esm.html which does not do this.

The second issue occurs when using inline shortcuts (but not command mode). Backspacing and correcting will indeed prevent the inline shortcut, which is admittedly undesirable.

**Comment by stefnotch** [comment]
I'd like to fix the second issue regarding inline shortcuts (and shortcuts in general?), because I'm using a bunch of them in my application. Would a PR regarding this be appreciated? 

Furthermore, if it's not too much to ask, where should I look when trying to fix this?

**Comment by arnog** [comment]
Look for `resetKeystrokeBuffer()` in `commands.ts`. That's the call site that's causing the keystroke buffer to be reset when there's an "editing" command. A PR addressing this would definitely be most welcome. Handling "backspace" is probably not too hard, the other editing command (or changing the insertion point, then backspacing) are probably a bit more tricky.
