### ISSUE TITLE
Cross-Origin iFrame Bug

### ISSUE THREAD

**Issue by mgreminger** [arnog/mathlive#1982]
## Description

When a page with a math-field element is embedded in an iframe on a site at a different origin, keyboard input into the math-field does not work and generates console errors. I've created a minimum reproduction on code-pen [here](https://codepen.io/mgreminger/pen/eYPxdap). The issue is also shown in the screen recording below:

https://github.com/arnog/mathlive/assets/6439649/100c646a-d107-4a55-8464-265163d5efb2

**MathLive version**
0.94.3

**Operating System**
All

**Browser** 
All

**Comment by arnog** [comment]
I'm not sure I have a complete fix. AFAICT the CodePen you have cannot fully work, since the cross-origin policy correctly prevents access between the frame and the host document. However, I have implemented some resilience so that no runtime error will be generated. The virtual keyboard will not be functional in the embedded frame in this situation, though.

**Comment by mgreminger** [comment]
Yes, that did the trick, thanks! I just submitted a pull request to add a cross-origin iframe test that uses the physical keyboard. This is in addition to the current same-origin iframe test that uses the virtual keyboard.

**Comment by arnog** [comment]
OK, great. Thanks for the tests!
