### ISSUE TITLE
Blank keyboard on Safari / iOS 16

### ISSUE THREAD

**Issue by pegula** [arnog/mathlive#2010]
## Description

Clicking on a math-live field in iOS 16 shows a blank keyboard.

![IMG_0012](https://github.com/arnog/mathlive/assets/999831/fd32385e-4257-4612-a471-1515f0c912f5)

## Steps to Reproduce

1. Use a device with iOS 16
2. Go to https://cortexjs.io/mathlive/
3. Click on the first example math-live field

### Actual Behavior

A blank keyboard is shown

### Expected Behavior

The full math input keyboard is shown.

Note: rotating the device from portrait to landscape triggers some sort of update and the keyboard shows.  Similarly, sometimes attaching the safari dev tool to it seems to trigger the keyboard to be shown.

### Environment

**MathLive version**
MathLive 0.94.7

**Operating System**
iOS 16

**Browser** 
Safari

**Comment by pegula** [comment]
Tried this on 16.2 on the simulator and everything seems ok.  Not sure what the usage stats are / how unused 16.0 is. 

Please close / disregard if 16.0 is not in the target window.

**Comment by arnog** [comment]
I suspect the issue was fixed in iOS 16.1 with "Fixed handling layout and paint containment", from the Safari release notes.

Only the last two versions of evergreen browsers are supported (Safari 16.5 and Safari 16.4) but there was a request to support 16.2, so a workaround was added to support it. There is no clear workaround for this issue (note to self: the CSS `container-type` property is the trigger).
