### ISSUE TITLE
ignore tab to previous/next element when at first/last position

### ISSUE THREAD

**Issue by shareefalis** [arnog/mathlive#2055]
## Description

in `commands-move.ts` 

```
      //
      // 1/ If at the end of the matfield, leap to next tabbable element
      //
      if (
        model.position === model.lastOffset &&
        model.anchor === model.lastOffset
      )
        return leap(model, 'forward');
```
```
     //
      // 1/ If at the start of the matfield, leap to previous tabbable element
      //
      if (model.position === 0 && model.anchor === 0)
        return leap(model, 'backward');
```
is there a way i can ignore or make it configurable without modifying the library?

**Comment by arnog** [comment]
Sure. You can listen for a tab key, and if the cursor is at the end of the mathfield, cancel the event.

**Comment by shareefalis** [comment]
I can do that, thank you. Maybe, make it configurable so we don't have to resort to cancelling the event?

**Comment by arnog** [comment]
Configuration options can get really complicated. Do you need an option for both the behavior at the end and start of the field? What do you want this configuration to control, i.e. what should happens when tab is pressed in those positions? Should it go to a next field, play a `plonk` sound, wrap around to the start of the field, go to the next tabbable position inside the field...? Using an event handler allows you to intercept the situation and handle it exactly how you want. When you `preventDefault()` the event, you're just saying: "the default behavior has been overridden". It's a simple and consistent way of handling customized behavior.

**Comment by arnog** [comment]
Question answered. Closing.
