### ISSUE TITLE
Pressing Tab key in 'fill-in-the-blank' does not move to next one

### ISSUE THREAD

**Issue by Deseux** [arnog/mathlive#2184]
fillInTheBlanks is great and you can move from one field to another using the keyboard arrows. But I would like to be able to do it with the tab key. Is it possible ?

**Comment by arnog** [comment]
Thanks for filing this issue. A bug report is always helpful to keep track of and resolve issues. 

In this case the issue was pretty clear and we had a discussion on Discord about it, so I had some context, but ideally a report would include at least:
- some code that I can use to debug the problem
- some step by step instructions for me to follow to reproduce the problem
- a clear description of what happened vs what you expected

Without this information it can take me considerably more time to investigate and fix an issue (or never fix it at all).

When creating an issue, following the instruction in the issue template is a good way to make sure the report includes all the necessary information. 

As an example, here's the same issue following the template:

---

## Description

Pressing the `Tab` key when inside a "fill-in-the-blank" does not move the focus to the next "fill-in-the-blank" in the page.


### Steps to Reproduce

1. Using the following code fragment:
```html
<math-field readonly>
   \frac{\placeholder[numer]{1+x}}{\placeholder[denom]{x-1}}
</math-field>
```

2. Position the cursor in the numerator "fill-in-the-blank"
3. Press the `Tab` key

### Actual Behavior

The focus stays in the numerator "fill-in-the-blank".

### Expected Behavior

The focus should move to the denominator "fill-in-the-blank".
