### ISSUE TITLE
Characters inserted after a \mathbb{} inherit the blackboard style

### ISSUE THREAD

**Issue by mathematicswizard** [arnog/mathlive#2402]
When you write in a mathfield:
\lbrace 2x\mid x\in\mathbb{R} then click enter
and then }
and afterwards you revert to the latex by ESC, you see this:
\lbrace 2x\mid x\in\mathbb{R\rbrace}

What would have been expected is this:
\lbrace 2x\mid x\in\mathbb{R}\rbrace

Upon examining it seems that although one closes the \mathbb{} with a right curly bracket - it includes everything that comes after it inside as an argument for the mathbb.

To wit:
![image](https://github.com/arnog/mathlive/assets/89847404/1d62699a-9fa9-4455-af97-4497ab867bbb)

**Comment by mathematicswizard** [comment]
I see in the changelog that it was published in the latest version. But there problem is still there. If you use the virtual keyboard and write \mathbb{N}\subseteq\mathbb{R} (but again only using the virtual keyboard) - things will look okay, but if you escape the text to see latex underneath you will see: \mathbb{N\subseteq R}.

**Comment by parkeraddison** [comment]
+1 this bug is still in effect. For example, in the demo https://cortexjs.io/mathfield/demo enter <kbd>\mathbb{E}</kbd> and notice the parsed LaTeX `\mathbb{E}`, then enter <kbd>_D</kbd> and notice that the LaTeX `\mathbb{E_{D}}` -- with the subscript inside the formatting bracket.

This seems to only affect superscript and subscript. This seems to affect bold, italic, blackboard, mathrm, etc. all formatting. Pressing escape (twice), right-arrow, tab, etc. doesn't seem to circumvent the issue.

### Workaround
1. For now, I've been doing something similar to https://github.com/arnog/mathlive/issues/179. Insert a `{}` or `~` (math mode required to prevent these from being auto-converted), then the LaTeX looks a bit strange but it allows you to achieve your desired result of sub-/super-script outside of the formatting.

    E.g. my custom inline shortcut looks like `"EE": "\\mathbb{E}{}"`.

2. If you press <kbd>Escape</kbd> to math mode, then <kbd>_</kbd> then <kbd>Enter</kbd> the script is placed after the closing formatting bracket, and you can cursor back into the script. Though this interrupts the writing flow significantly.

### Fixing
For myself, I would expect bolding to end once sub-/super-script begins. A config flag would also make sense.

This bug present a slightly broader question as to whether there should be a clearer indication as to whether the cursor is currently inside or outside of a hidden bracket pair.
