### ISSUE TITLE
need custom locale support, manual mode in popover

### ISSUE THREAD

**Issue by Paosder** [arnog/mathlive#262]
### Description
Need to support l10n in popover to change locale strings(hint). And also need to add manual mode for control popover window. There's no option to control nor set any options related with popover window until now, and Latex descriptions are hard-coded in variable `SAMPLES` and `NOTES` in `editor-popover.js`. I think we can use l10n in popover to support other languages that we already had. Also we need to serve some options to control popover window so that we could use mathlive in tiny section without popover which wraps whole section.

**Comment by arnog** [comment]
Can you elaborate on what options to control the popover window you would like? Do you have an API in mind? If so, please share it.

**Comment by Paosder** [comment]
Like virtual keyboard `virtualKeyboardMode`, it needs option to control mode ( e.g `popOverMode` ) to control its appearing state. At least two modes are needed, `auto` and `manual` mode. `auto` is work as a default mathlive popover and `manual` is give a chance to developer to control its appearing time. Furthermore, another new option `popOverOptions`, control its theme or include or exclude other latex expression to describe, that would feel great to customize popover window. And also needed outer API to show or hide popover, like `$showPopover()` and `$hidePopover()`.

**Comment by arnog** [comment]
OK, that makes sense. I'm struggling a bit however with the option to control the list of suggestions to display in the pop-over. Since you are in command mode, any valid latex can be entered at this point. It would seem weird to not display a command in the pop-over, but let the user type it. Are you looking in general to prevent the entry of specific latex commands? Could you tell me more about your use case? Incidentally, I'm interested in understanding why you find the command mode useful, as oppose to the inline auto-complete, as I'm considering dropping the command mode altogether.

**Comment by Paosder** [comment]
I read new roadmap and I agree with your opinion that drop entire command mode because of its redundant and hard to keep code working. I just want to prevent some latex commands that do not needed in my app, also give a new 'commands' symbolic link to default commmands, for instance, `\square_root` to `\sqrt`. It may sounds very weird(WHY JUST USE `\sqrt`?!), however in different locale, language, these features will give more powerful to use for end-user(especially, young students).

**Comment by arnog** [comment]
You can already define new commands by using the `macros` config property. For example:
```javascript
   mf.$setOptions({macros: {'square_root': '\\sqrt{#1}'}});
```

You can also control which inline shortcuts are recognized. Set the `overrideDefaultInlineShortcuts` config property to `false` to turn off the default inline shortcuts, then use the `inlineShortcuts` config property to define only those inline shortcuts you want.

This should give you the customization you're looking for, but let me know if you need more.

**Comment by Paosder** [comment]
@arnog 
I couldn't found `$setOptions` in mathfield ref, either in source code, but I found `macros` as you mentioned. It works great but it seems supports only English not just any text therefore I couldn't use with other languages. Actually, that was what I'm looking for(+ control popover manually).

**Comment by arnog** [comment]
My bad, it's `mf.$setConfig()`.
I don't understand what you mean by "it seems support only English". It defines a TeX macro, so any valid TeX command name would work. You cannot use non-ASCII characters because those are not valid TeX command names. Could you share the code of what you tried to do and what happened?

**Comment by Paosder** [comment]
> I don't understand what you mean by "it seems support only English". It defines a TeX macro, so any valid TeX command name would work. You cannot use non-ASCII characters because those are not valid TeX command names.

Yes, all I want to do is input non-ASCII characters(e.g any other languages without alphabet, `\제곱근`) and link it using `macros` feature. However in inline command mode, any characters without alphabet will fail to input in edit area(but it works in text or math mode) and I want to resolve that issue.

**Comment by arnog** [comment]
You should be able to define inline shortcuts using non-ASCII characters, including CJK. Have you tried `mf.$setConfig({inlineShortcuts: ['제곱근', '\\sqrt']})`?

**Comment by Paosder** [comment]
Yup, I tried but it fails. It only works with alphabet. 

![prob1](https://user-images.githubusercontent.com/20926881/66818306-180b0480-ef78-11e9-97d0-131138497543.gif)

Here's my code:
``` javascript
      const newMathField = Mathlive.makeMathField(targetRef.current);
      newMathField.$setConfig({
        virtualKeyboardMode: 'manual',
        defaultMode: 'text',
        inlineShortcutTimeout: 0,
        inlineShortcuts: {
          ㄱ: '\\sqrt',
          sq: '\\sqrt',
          ㄱㄴ: '\\sqrt',
        },
        virtualKeyboards: 'all',
     });
```

**Comment by arnog** [comment]
This appears to be working now. There were several improvements in that area of the code that could explain this. I have tested it with a keyboard with a Korean layout and typing ㄱ triggers the insert of a square root as expected. Note that  "ㄱㄴ" cannot be triggered since it begins with "ㄱ" which is already assigned. However, if the definition for "ㄱ" is removed "ㄱㄴ" triggers the shortcut as expected.
