### ISSUE TITLE
MathLive element rendering delayed

### ISSUE THREAD

**Issue by zoranpopovic** [arnog/mathlive#333]
In our application we do some followup rendering around the equation that depends on the position of math content (we use `\cssId` for locating key elements).  However, this doesn't work
```
MathLive.renderMathInElement("description");
render(); 
```
as the we get locations of elements that are not fullly reflowed.  This, however, works:
```
MathLive.renderMathInElement("description");
setTimeout(render, 200);  
```
So math rendering takes some time.  Is there a way to get a callback or some other way to know where math rendering is fully complete?

**Comment by arnog** [comment]
The delay in the rendering is probably due to the asynchronous resources, in particular, the fonts.
You have two possible paths: pre-loading those resources before attempting to render, or listening to an event signaling the loading of the fonts (https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet).

**Comment by zoranpopovic** [comment]
Thanks this was the most compact thing that worked:
`document.fonts.ready.then(this.renderDecorations);` when`renderDecorations` is called everything is in its final typesetting position.
