### ISSUE TITLE
enclose draws poorly

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#34]
## Description

The way cross outs (using `\enclose`) are drawn makes is hard to tell what is crossed out. E.g., in the following, the entire (complex) fraction is being crossed out, but that's not obvious from the rendering:
![image](https://user-images.githubusercontent.com/1545836/32426592-4c420186-c270-11e7-87e8-bc0f246d8cf5.png)

Here's the latex for that example:
`\enclose{updiagonalstrike downdiagonalstrike}[2px solid red]{\frac{a}{\frac{b}{c}}}`

I think it would be best to draw the diagonal strikes from corner to corner of the bounding box. That would correspond to what the MathML spec says

> The values "northeastarrow", "updiagonalstrike", "downdiagonalstrike", "verticalstrike" and "horizontalstrike" should result in the indicated strikeout lines being superimposed over the content of the menclose, e.g. a strikeout that extends from the lower left corner to the upper right corner of the menclose element for "updiagonalstrike", etc.

**Comment by NSoiffer** [comment]
Looking at the code, the vertical extents used for the cross outs are the same as the ones used for `verticalstrike`. That looks really bad:  
![image](https://user-images.githubusercontent.com/1545836/32463169-d669b428-c2f0-11e7-9138-afd50b97057b.png)

Here's the latex for that:
`\enclose{verticalstrike}[2px solid red]{\frac{a}{\frac{b}{c}}}`

Note: `top`, `left`, `right`, `bottom` use borders, and so they don't have this problem

**Comment by arnog** [comment]
I started from scratch with a new implementation of \enclose. The previous approach relied on measuring the element on which the annotation was overlaid in order to correctly size and position the SVG overlay. However, doing this measurement accurately is just too difficult to get right.

With this new approach, the SVG overlay does not depend on the size annotated element, but instead uses relative percentages to draw the annotation. The downside of this approach is that some annotations, including updiagonalarrow, phasorangle, radical and longdiv are no longer supported. However, for many common cases, the annotation should look better.
