### ISSUE TITLE
Supsub issue: ax^2 should not be {ax}^2

### ISSUE THREAD

**Issue by ChillingVan** [arnog/mathlive#372]
## Description

When input ax and then input ^2, the latex will become {ax}^2 instead of ax^2

### Actual behavior

For example:
![图片](https://user-images.githubusercontent.com/7666419/73936510-f9ad8800-491d-11ea-920e-eddd11bdda94.png)

### Expected Behavior
The latex should be ax^2 or a{x}^2 instead of {ax}^2

### Environment

**Operating System**
[macOS, Windows, iOS]

**Browser** [Safari, Chrome, IE, Firefox, etc...]

**Comment by ChillingVan** [comment]
I understand the original design for this is for multiple number:
89^2 will be {89}^2

**Comment by arnog** [comment]
I cannot reproduce this.
I used the basic example (examples/basic/index.ems.html), typed "ax^2", and I got "ax^2" as the LaTeX output.

**Comment by arnog** [comment]
Ah, OK, I can reproduce this now:
1/ Use examples/basic/index.esm.html
2/ Click on the virtual keyboard button
3/ Type "a", "x", then "x^2"
4/ Result -> "{ax}^2"

**Comment by ChillingVan** [comment]
Yeah, using virtual keyboard can reproduce it.
Currently it seems that it is caused by this code:
![图片](https://user-images.githubusercontent.com/7666419/73945038-9c6e0280-492e-11ea-9a6a-ae2f94e5a4c0.png)

I will dig more tomorrow.

**Comment by arnog** [comment]
The issue is in the parser.

I've changed the behavior of the parser to not insert a group when substituting a multi-token argument. 

E.g. "x#1 y" when the argument is "abc" used to produce "x{abc} y", it now produces "xabc y".

This seems to be consistent with the TeX behavior, but I'm a bit concerned that this change could have unintended consequences and may need to be revisited.
