### ISSUE TITLE
Pressing < key in a german keyboard adds a \ instead

### ISSUE THREAD

**Issue by nkipi** [arnog/mathlive#417]
## Prerequisites

-   [ ] New issue

## Description

On a german keyboard if you pres the key that normally types `<`, it would insert a `\`.

### Actual behavior

![lessThan](https://user-images.githubusercontent.com/28009381/79250672-4f069800-7e7f-11ea-8b8b-3627aa1b350f.gif)

### Expected Behavior

I expect that it normally adds a `<` as it should. On a german keyboard one can type `\` on a separate key already. And the english keyboard also has a separate keys for `\`, `<` and `>`. 

## Steps to Reproduce

1. Switch your keyboard to german.
2. Try to type < in the mathlive input by pressing this key.
![image](https://user-images.githubusercontent.com/28009381/79250909-b91f3d00-7e7f-11ea-818e-721c4e9ca688.png)

### Environment

**Operating System**
[Windows]

**Browser** [Chrome,Firefox]

**URL** [https://mathlive.io/]

**Comment by arnog** [comment]
I haven't been able to reproduce this. 
Are you using a physical keyboard? 
What is the key that is immediately to the right of the <> key? 
What happens if you press the ESC key? 
What happens if you press shift+<> ? 
In your screencap it appears as if the first time you press the <> key you enter command mode, then subsequently when you continue to press that key you get the correct "<"? Is that right?

Note that it appears as if the key you are pressing is triggering an escape character which enters the command mode (and result in a \ being inserted).

**Comment by Khazuar** [comment]
I can confirm this. I've got a physical German keyboard, that I usually set to English keyboard layout for programming. The situation is complex, I assume the problem is that the German keyboard has slightly different physical keys (positioning and amount) than the English one.

![20200419_102111](https://user-images.githubusercontent.com/3444034/79683062-a1510b80-8227-11ea-8051-c0e1d1b02b8b.jpg)

When I set the keyboard to English a number of keys swap their places, usually for the better (especially for programming). The weird shape of the "Enter"-key on German keyboards make the key-bindings there a little strange though compared to a physical US-keyboard. The key labeled with `#` and `'` produces the `\` (and `|` when holding shift) and is located about where the equivalent on a physical US keyboard would be. But then, there's also the key labeled with `<`, `>` and `|` in the lower left of the keyboard that doesn't seem to have a physical equivalence on US keyboards. On US-layout, that one will produce `\` and `|` as well.

When I press that strange button with my keyboard set to German, Mathlive switches to command mode first and then types `<` for subsequent presses. Interestingly, adding 
```
inlineShortcuts: {
  "<": "<",
},
```
**fixes this strange behavior completely**. Is the command-mode maybe triggered by the keycode or something rather then by what the current keyboard layout is producing?

**Comment by arnog** [comment]
Note to self: when switching to the German layout, it's the "~/ `" key on my M65-A keyboard.

**Comment by arnog** [comment]
OK, I've found the issue. This key is called `IntlBackslash` (long story, I know it's not a backslash on the German keyboard, but I don't make the standards, and it *is* a backslash key on British keyboards. And this key doesn't exist on US keyboards: the use keyboards have a different key called `Backslash` :) ). And `IntlBackslash` is very explicitly mapped to switch mode:

**`editor-shortcuts.js: 106:`**
``` javascript
    'math:IntlBackslash': ['switch-mode', 'command'],
```
That works for the UK, but obviously it introduces the problem in this report. Sigh.

I'm going to remove this shortcut. That will address the issue in this report. British users will still be able to use the `escape` key to enter command mode.

**Comment by arnog** [comment]
Oh, no, internationalization *is* super fun. It's a great opportunity to learn and discover about differences 
in things big and small around the world.

The somewhat frustrating thing is that to this day the web API for international keyboard handling are... lacking. For example, there's no way to programmatically find out the keyboard layout a user is using. Admittedly, for 99% of developers, this is not important and the existing API are sufficient. When you try to do things a bit more in depth with keyboard input, though... Oh well. 

I do plan to drop the command mode, so this particular issue will become moot. But I do hope at some point to add an API for custom keyboard shortcuts, at which point I'll need to think of something reasonable to do with keyboard shortcuts in general.

**Comment by arnog** [comment]
This should now be fixed.
