### ISSUE TITLE
Feature: load fonts from a custom folder

### ISSUE THREAD

**Issue by arnog** [arnog/mathlive#425]
## Description

For some deployment configurations, the fonts need to be placed in a specific folder different than the default `fonts/` folder.

Provide a mechanism, such as a `fontFolder` option in the `config` object, to dynamically load the fonts from a specific URL.

**Comment by spirobel** [comment]
Thank you very much! That would mean I dont need to keep the fork with the changed CSS variables around. Another issue that came up is the z-index value of the keyboard: [ collect z-index of keyboard in one variable #433 ](https://github.com/arnog/mathlive/pull/433)
maybe you can also add an option for this. 
A discourse user asked for a math editor similar to this:
[picture of editor](https://d11a6trkgmumsb.cloudfront.net/original/3X/5/8/58ef1a75f29012b59dc00c59cc563b66af9a71a4.png)
So it seems like they want to have an editor directly below the input field. Do you think it would be hard to position the keyboard next to the input field instead of the bottom of the screen? This is not really urgent, it will work the way it is right now, but I think it could help some beginner users if they dont need to activate the keyboard first and the buttons are right next to the input field.
Thanks again for your help. This helps a lot! :smile:
