### ISSUE TITLE
Issues with display in array mode when adding a new line

### ISSUE THREAD

**Issue by rmeniche** [arnog/mathlive#460]
## Prerequisites

-   [ :+1:] New issue

## Description

Hello ! We're using array format in order to declare informations, for example an exercice, in this exercice there could be multiple lines that refer to mathematical rules for example. This rules are meant to be described by the teacher when he declares an exercice. There can be 0 or more rules for this exercice.

I'll show you an example directly.

![](https://i.imgur.com/q4UWKzy.png)

In this example, I want to add a new line after the c at the 5th line.

### Actual behavior

When I use escape in order to add a new line it creates a new line after the last line. The cursor goes there too.

### Expected Behavior

I expect it to create a new line between the abc line and the Data line.

## Steps to Reproduce

1/ Go to examples/virtual_keyboard/index.html
2/ Edit a button in a HTML Keyboard with this
```
   <li class='keycap' data-insert='\begin{array}{lcl}\text{Title : } & \text{ ? } & &
    \text{Rule : } & & & & & &
    #? \to #? & \text{Condition : } #? & \text{Feedback: } \text{ ?} & a & b & c &
    \text{Data : } & & &
    \text{Transformation} & \text{Conditions  } & \text{Feedback} & & & &
    #? & #? & \text{ ? } &
    \text{Question : } & \text{ ? } & &
    '>exercice</li>
```
3/ Go to localhost 
4/ Use the button and use escape to add a new line with the cursor after c

### Environment

**Operating System**
Windows10

**Browser** 
Mozilla

**Comment by arnog** [comment]
This is the correct behavior.

Here's why it happens:
- you have specified a matrix with three columns (`{lcl}`).
- however, the matrix you specify actually has 1 row and 30 columns (each `&` indicate a new column)
- Latex does its best to display this matrix, by displaying a new line every three columns
- When you insert a new line (by pressing the [Return] key in the `c` cell), the new line is inserted after the first line of 30 columns

To fix this, you need to explicitly specify the end of rows, instead of having extra columns. That is, change `c &` to `c \\` (and so on for each of the rows you want).

**Comment by rmeniche** [comment]
Oh okay I see, my bad, sorry for this.
Thanks you !
