### ISSUE TITLE
mathlive not working in IE

### ISSUE THREAD

**Issue by asaltrader** [arnog/mathlive#478]
Hi
I use mathlive with vue-js and it's work fine in firefox and chrome
but it's not working in IE (v11)
and that's cause it didn't load vuejs ( doesn't show nothing in my page )

**Comment by arnog** [comment]
IE is not supported, but if you'd like to submit a PR with a fix, I'll be happy to consider it.

**Comment by seanjrankin** [comment]
@arnog We needed our app to at least load in IE11. 

We got it working by adding an extra babel polyfill '@babel/plugin-transform-spread' and also had to create a fork to fix the failing Regex:

https://github.com/arnog/mathlive/compare/v0.52.0...showbie-socrative:0.52-soc
(0.52 because we can't yet move to the latest version using `import.meta`. Another issue to discuss)

IE11 can't parse the `new RegExp('\\p{Letter}', 'u')`

**Comment by arnog** [comment]
ok, great.
