### ISSUE TITLE
How to access Atom via atomID?

### ISSUE THREAD

**Issue by leontepe** [arnog/mathlive#479]
Is there currently any function/method in the source code of MathLive that returns the atom (or atom**s** in the case of highlighting) for a specified atom ID? I can't seem to find a way of accessing the Atom object corresponding to a particular span by the current implementation of `ModelPrivate`. What is the best way to go about achieving this?

**Comment by arnog** [comment]
```
function findAtomFromId(id: string) {
    return filter(model, (_,atom) => atom.id === id)?.[0]
}
```

**Comment by leontepe** [comment]
@arnog where is the `filter` function that you referenced located?

**Comment by leontepe** [comment]
What about highlighting, though? Wouldn't the function have to return an array of atoms (since they share a common `atomID`)?

**Comment by leontepe** [comment]
Also, is there any resource explaining how the whole model structure of the mathfield works? Or could you explain it? I've been looking through the source code for a few hours now and I'm still mostly groping in the dark.

**Comment by arnog** [comment]
> What about highlighting, though? Wouldn't the function have to return an array of atoms (since they share a common `atomID`)?

Each atom has a unique ID. The atom ID is not shared. I don't know what you're trying to do. Maybe have a look at `pathFromPoint` in `mathfield-pointer-input.ts`?

If you want all the atoms that are selected:
```typescript 
   model.root.filter(atom) => atom.isSelected );
```
This will return an array of Atom.

Have you read the CONTRIBUTOR_GUIDE? There's some info in it about the model and how it relates to other data structures. Maybe that will help a bit? Otherwise, let me know what you are trying to do and I'll try to answer your questions. Feel free to make edits to the documentation as well as you discover things that weren't clear. It's all pretty clear to me, but I'm biased :)

**Comment by leontepe** [comment]
> Each atom has a unique ID. The atom ID is not shared.

I am talking about the highlighting for the speech / read aloud system (`editor/speech-read-aloud.ts`). As far as I understand it, it uses a single atom ID for groups of numbers, for example (to highlight them simultaneously when reading the formula aloud).

Since I wanted to achieve the same grouping effect for my application for now, I set up `forHighlighting: true` in my options object in the `render(...)` call of my custom mathfield and thus it now uses "shared" IDs as well.

And that's why I was thinking whether it should rather return an array of atoms, in this case... 🤔

**Comment by leontepe** [comment]
And: I have read most of the Contributor Guide, yeah. But one thing I didn't figure out is how the actual core logic there is implemented and what kind of sense the main functions used to navigate the model (`parent()`, `siblings()` etc.) make. I would have expected the `Atom` class to have a `children` property to construct a tree (like an AST). But since this is not the case, I am very confused and am having a hard time.

**Comment by arnog** [comment]
Ah, yes, the `forHighligthing` mode will group multiple spans into one (i.e.for numbers) so they can be highlighted as one. Note that in this mode the equation is not editable (because the id<->atom connection is broken).  In this situation there may be multiple atoms with the same ID (don't remember if that's the case or not).

`Atom` is a "standalone" object. It doesn't have a parent and doesn't really have children (it has multiple "strands" of children, via `body`, `superscript`, `index`, etc...). This was meant to reflect the rendering model of Latex, but it's a design decision I regret and hope to rectify at some point.

Because of this, to keep track of "where" in the rendering tree the selection is, or more generally to "address" a particular atom in the tree a "path" is used, which is a data structure indicating how to reach any atom in the expression, starting from the root: "start at the root, then take the second child on the body, then the 3rd child on the superscript".

To find the "parent", you go "up" in the path. In the example above, you would remove the last segment ("3rd child on the superscript") and you find yourself on the parent ("start at the root, then take the second child on the body").

Given this, the "siblings" represent the adjacent atoms that share the same parent.

This also makes keeping track of the selection and changing it harder than it needs to, but it basically involve making change to the "path" (and the extent, which represent how many siblings from the path the selection is extended by).

Hope this helps.

**Comment by leontepe** [comment]
Ohh, now I understand what all of this path-stuff is about. This was confusing me so much. 

> It doesn't have a parent and doesn't really have children (it has multiple "strands" of children, via body, superscript, index, etc...). This was meant to reflect the rendering model of Latex, but it's a design decision I regret and hope to rectify at some point.

Since you mentioned it: how else would you implement it this time? Since I am making a "simpler" version of a mathfield that doesn't need to keep track of selection, I might have the freedom to implement it in the way you'd do it this time.

Also, just to make sure I understood it right: so `parent()` and `siblings()` always refer to the parent and siblings (respectively) of the atom that is currently "adressed" via `path`?

**Comment by arnog** [comment]
> Also, just to make sure I understood it right: so `parent()` and `siblings()` always refer to the parent and siblings (respectively) of the atom that is currently "adressed" via `path`?

Yes. The `path` represent the current insertion point (or head of the selection), and `ancestor()`, `parent()`, `siblings()` etc.. refer to the "relatives" of the atom pointed at by `path`.

> Since you mentioned it: how else would you implement it this time?

I would add a parent field to Atom so that a tree (graph) of atoms can easily be navigated and I would use a simple offset counting scheme to represent the caret.

**Comment by leontepe** [comment]
Okay, thank you. This helped me a lot! :)

**Comment by NSoiffer** [comment]
Back in the 90s when I wrote the math editor for Mathematica, I used shared
nodes and relative positions to save space: 8mb RAM was a lot and
Mathematica generates lots of shareable subexpressions. It did save *a lot *of
space for larger outputs, but keeping track of the path (I used a depth
first count to produce a selection range) added a ton of complexity to the
code. The code has since been converted to use parent pointers and I
suspect it got much shorter. I believe the cursor/selection is now
represented by simple pointers to the first/last char node that is selected.

That's my history :-)

    Neil

**Comment by leontepe** [comment]
@NSoiffer so, are you saying you would also suggest using a standard tree-like structure with parent pointers and children lists as well? 🤔

**Comment by NSoiffer** [comment]
Yes.

**Comment by leontepe** [comment]
@NSoiffer but wouldn't this break the goal of MathLive (as I understood it) to replicate the behavior of TeX as closely as possible? Although I agree that the current way it seems to be implemented is rather unwieldy, isn't it closer to TeX original way of typesetting?

**Comment by NSoiffer** [comment]
I don't believe Arno is trying to replicate TeX's internal structure; the current version doesn't. TeX's structures were never meant for WYSIWYG editing.

**Comment by arnog** [comment]
The intent of MathLive is to replicate the layout that TeX implements. Certainly not the internal data structures which were conceived when the computing environments where *extremely* different. And as Neil points out, TeX was never meant to be interactive. I initially avoided introducing a tree structure (specifically a parent pointer in Atom) because TeX did not have it and does not need it for its layout (which is basically one pass without the need to backtrack to the ancestors). However, it is very convenient to have when you need to frequently traverse the data structure, in particular for editing. As both Neil and I have demonstrated it is possible to live without it (using a separate "path" structure), but the code is both simpler and easier to maintain when using an actual parent pointer.

**Comment by leontepe** [comment]
So, how would you go about implementing these changes? As far as I see, you still can't have a "liberal" tree structure since you need to still keep track of the "special children", the fields, namely superscript, subscript and nucleus, right? How would you go about making these changes, as a rough outline?

**Comment by arnog** [comment]
I'm not sure, I'd have to think about it more. But I would start with adding a `parent` field to the `Atom` class.

**Comment by arnog** [comment]
Question has been answered, closing.
