### ISSUE TITLE
Spacing is inconsistent after editing

### ISSUE THREAD

**Issue by bengolds** [arnog/mathlive#504]
## Description
Spacing between arithmetic can be either quite large, or quite small after editing. A quick repro is to type in "3+4", delete the 3, and replace it with another number. 

[Safari](https://brilliant-staff-media.s3-us-west-2.amazonaws.com/ben-goldsmith/Screen-Recording-2020-06-15-17-40-33.mp4)
[Chrome](https://brilliant-staff-media.s3-us-west-2.amazonaws.com/ben-goldsmith/Screen-Recording-2020-06-15-17-42-54.mp4)

### Environment

**Operating System**
macOS, 10.15.5

**Browser** 
Safari & Chrome

**URL** [URL where the problem can be reproduced, if available]

**Comment by arnog** [comment]
OK, this turned out to be an interesting and embarrassing issue.

The spacing of operators should be adjusted depending on what's around them: there is less space after a "-" sign when used as an infix operator than there is around a "-" sign used as a prefix operator (i.e. "-4" vs "3-4").

The code that was handling this was accounting for it by modifying the type of the element. This worked well enough for static rendering, but for dynamic rendering (i.e. editing), once modified the previous type of the element was lost and could not be restored (i.e. after deleting the atom in front of a "-" sign, the "-" was no longer a binary operator but a regular symbol).

The solution for this is of course to *not* modify the type of the element, but rather to account for the elements surrounding it at rendering time.

AFAICT this has been in MathLive since forever, and I can't believe I never noticed this.
