### ISSUE TITLE
Selector for tooltip styles should be scoped

### ISSUE THREAD

**Issue by stormwarning** [arnog/mathlive#519]
## Prerequisites

-   [x] New issue

## Description

The selector used for styling tooltips — https://github.com/arnog/mathlive/blob/f4b6adeea0ba2eb3a24522d9d1d6aa1b3b671be0/css/mathfield.less#L292 — is very broad and can (or *does* in my case) conflict with existing components/styles. The specificity is low so it can be worked around, but ideally these styles would be scoped to the MathLive lib.

Happy to add a PR for this once a better selector is determined. Seems like there's not a single scope that would suit from a quick look. Something like 

```less
.ML__fieldcontainer,
.ML__keyboard {
  [data-tooltip] {
```

would probably work.

**Comment by arnog** [comment]
Good idea. I would suggest using `data-ML__tooltip` instead of `data-tooltip`. It requires a few more changes in the code base (but they're all easy to find, look for `data-toolip`) but simple CSS rules (lower specificity) are generally better (faster for browsers to handle).

If you a submit a PR for this I'll be happy to merge it in.
