### ISSUE TITLE
Definition files are wrong

### ISSUE THREAD

**Issue by Khazuar** [arnog/mathlive#590]
In your definition files (`.d.ts`) the utility-functions are still exported on root level (see https://github.com/arnog/mathlive/blob/master/dist/public/mathlive.d.ts#L87), while in both the `.js` and `.mjs`-files they are part of the default-export (like it's defined in https://github.com/arnog/mathlive/blob/master/src/mathlive.ts#L298). Seems like the typings are not generated/emitted correctly?

**Comment by arnog** [comment]
The intent is that if you `import Mathlive from "mathlive"` you can then call `Mathlive.makeMathField()`, but that you can also do `import {mathMathField} from "mathlive"` and call `makeMathField()`, the former being the backward compatible scheme, and the latter being the more "module-native" one. Is this not what's happening?

**Comment by arnog** [comment]
OK, I see. So rather than "Definition files are wrong", I think the issue is that there's a spurious `export` in front of `function makeMathField` in `public/mathlive.ts`. 

The intent is still to migrate those to be top-level public export and to move away from using `default` exports, but I'll do that a bit later along with a pass to rename some of those functions. In the meantime, this `export` keyword was a bit too early, since it did not match the definition of `makeMathField` in `src/mathlive.ts`.
