### ISSUE TITLE
German Umlaute in `\text{}` get removed

### ISSUE THREAD

**Issue by Khazuar** [arnog/mathlive#599]
## Description

German umlaute in pasted text-areas like `\text{für}` get removed. Inside `\operatorname`s they remain in latex, but don't show either.

![image](https://user-images.githubusercontent.com/3444034/91535607-b0ea0a80-e913-11ea-9983-fc08c9e75370.png)

### Expected Behavior

This used to work fine in the 0.35.x-versions.

## Steps to Reproduce

Paste `\text{für}` into the mathfield on mathlive.io.

### Environment

**Operating System**
Windows 10

**Browser**
Chrome

**Comment by arnog** [comment]
It's not unreasonable to expect this to work, but note that this is not valid LaTeX. The proper LaTeX for it is `\text{f\"ur}\operatorname{f\ddot{u}r}`, although this LaTeX doesn't work in MathLive either. 

`$$\operatorname{f^^fcr}$$` works, though.

**Comment by stefnotch** [comment]
I decided to have a look at this.

So, the issue seems to be that it's trying to get some information about the character in text mode
https://github.com/arnog/mathlive/blob/be533c9ea6fef282a34f70677fa61f979b3bef5e/src/core/modes-text.ts#L297

However, that fails since the German `ü` isn't in the `TEXT_SYMBOLS`, so info stays null.
https://github.com/arnog/mathlive/blob/be533c9ea6fef282a34f70677fa61f979b3bef5e/src/core/definitions-utils.ts#L857-L859

Now, the question is: What's the correct way of fixing this? Adding the German letters to the dictionary? Accepting just about everything in `\text{}`, just like you can enter pretty much anything in math mode? Or something different?

I've tested a few LaTeX variants (pdfLaTeX, LaTeX, XeLaTeX) and most of them accept the characters. 
e.g. pdfLaTeX seems to accept quite a lot (even though it complains that there are errors)
```
\begin{equation}
    aa=b\text{3_5test&^ für©Ââ Êê Îî Ôô Ŵŵ Ŷŷ Ïï}
\end{equation}
```
![image](https://user-images.githubusercontent.com/10220080/93004062-f62d4f80-f543-11ea-8ded-1f1d5b0c0ba8.png)

Meanwhile XeLaTeX for some reason really doesn't like the special characters
![image](https://user-images.githubusercontent.com/10220080/93004099-355ba080-f544-11ea-9c10-6a76f35e7ae7.png)

**Comment by arnog** [comment]
XeLaTeX is the closest to the original TeX behavior. Nowadays, however, it is perhaps not very desirable. It would be reasonable to allow non-canonical characters (i.e. characters that don't map to a `TEXT_SYMBOLS` or `MATH_SYMBOLS`) and map them to a reasonable TeX command (either `\char` or or `^^` `^^^^`) for maximum interoperability.

Have a go at it if you'd like. It should be fairly straightforward.
