### ISSUE TITLE
Problems with \rlap

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#6]
## Description
There are a number of problems with \rlap

### Startup
If a file contains an editor instance (*not* static math[!]) which is $$\rlap{/}{7}x$$, then when it is displayed, the "/" does not overlap and it displays as "\7x".

### Copy
If I type \rlap{/}{7}x in the editor, the display is fine. If I select it and copy it to a text file, the rlap is missing and only "7x" shows up. If there is something in front of the \rlap (e.g., "x+\rlap{/}{7}x"), the same thing happens. Hence, it is not a matter of not selecting the rlap.

### Edit
This may not be a bug, but it is definitely not intuitive... 

With the expression \rlap{/}{7}x, click at the start of the expression. There is no way to add something that doesn't become the argument of the \rlap. E.g., If I type "x", it has the slash on top of it. No matter what is typed (maybe also pasted) and no matter in what order, the first character always has a slash through it. It is not possible to keep the slash in the '7' nor is it possible to type anything in front of the '7' without it having a slash. Neither backspace nor delete get rid of it either.

### Backslash (\\)
If  '\\' is the first arg, either as {\\} or {\\\\}, you don't end up with a "\\".  In the first case, you end up with a "}" and in the second, you end up with neither '\\'nor '7' displaying.

**Comment by arnog** [comment]
I've fixed the issue with copy. The LaTeX code for `\rlap` was not getting generated.

The issue with backslash is that \\ has a special meaning in LaTeX, which is "end of row". The correct command for a backslash character actually is `\backslash`, which wasn't working in the context of an argument to `\rlap`, but I've fixed that.

The issue you describe with Edit is a broader problem. Accents behave similarly. I need to think about this. Could you open a separate issue to track this?

I wasn't able to reproduce the issue you describe under **Startup**. Is it still happening for you? If so, could you provide a pointer to a sample?

**Comment by arnog** [comment]
Ah, I have a good guess for the Startup issue I couldn't reproduce earlier.

I believe you have a:
```html
<span id='editor'>$$\rlap{/}{7}x$$</span>
```
and that you call `MathLive.renderMathInDocument()` followed by `MathLive.makeMathField('editor')`. The problem is that the call to `renderMathInDocument()` renders the LaTeX to HTML, then when `makeMathField` is called it tries to make sense of the HTML and turn it into original content of the editor.

To fix this, a few options:
* Call `MathLive.renderMathInElement(...)` only on those elements you do want to turn into static content
or...
* add the class `tex2jax_ignore` to the editor span. This will prevent renderMathInDocument to attempt to render it.

**Comment by arnog** [comment]
I believe this issue has been addressed. If that's not the case, please reopen it or file a new one.
