### ISSUE TITLE
How to make the mathfield an inline element 

### ISSUE THREAD

**Issue by zwz** [arnog/mathlive#609]
## Description
I am trying mathlive in my editor:
1. rendering all the equations (readonly)
2. when any of them is clicked, a modal shows, where it can be modified

The second part is OK. https://mathlive.io/examples/ gives a lot examples of editing equations with mathlive.
While for the first part, I failed to render some simple and short equations as inline elements.

I did some test like
```
MathLive.makeMathField('testspan', {
     virtualKeyboardMode: 'off',
     readonly: true
   }).$latex('\\alpha')
```
and fiddled with the css style. But just could not make it.

**Comment by arnog** [comment]
I'm not sure exactly what the issue is. Do you have a codepen that demonstrates the problem?

A few notes:
- the `readonly` property is actually spelled `readOnly`
- if you are trying to have a difference appearance depending on whether the field is focused or not, the `ML__focused` CSS class is added to the currently focused mathfield
- if you only try to display some inline, non-editable, math, you do not need a mathfield. Your html should simply be something like `<span>$$\alpha$$</span>`, then call `MathLive.renderMathInElement()` (to render only one specific DOM element) or `MathLive.renderMathInDocument()` (to render all inline math in a document). You could also tag the desired elements with a specific class. See the [documentation for these functions](http://cortexjs.io/docs/mathlive/?q=renderMathInDocument%20renderMathInElement%20AutoRenderOptions) for more details.

**Comment by zwz** [comment]
It is rather a question than an issue.
I get the answer. Thank you.
