### ISSUE TITLE
Clicking in empty numerator causes placeholder to appear

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#64]
## Description
If you create a fraction and delete either the numerator or denominator, it is blank. But if you click in the empty slot, a placeholder appears. This seems wrong (clicking shouldn't change the appearance)

## Steps to Reproduce
1. Type `a/`. You see 
![image](https://user-images.githubusercontent.com/1545836/36862624-3ce35e48-1d3c-11e8-9a9f-d60e3fba645b.png)

2. Type delete to delete the placeholder. You see
![image](https://user-images.githubusercontent.com/1545836/36862661-5c2bc9fc-1d3c-11e8-9288-01c865eb80a0.png)

3. Click in the denominator. You see
![image](https://user-images.githubusercontent.com/1545836/36862717-86ac3c84-1d3c-11e8-86dd-7c29457577fa.png)

A similar thing happens for the numerator.

**Comment by arnog** [comment]
The issue seems to be that since the denominator is empty, you're actually not clicking on it, but on an adjacent node, therefore leaving the denominator, and causing the placeholder to be inserted.

I'm not sure of what the right behavior would be. Not inserting the placeholder would also require not changing the selection, and this would mean that the "empty" denominator would have to be considered to have a margin around it where clicking would be a no-op. This in turn would have the side effect of actually changing the selection more difficult. Is this really the right behavior?

**Comment by NSoiffer** [comment]
The current implementation seems to favor the notion that an empty denominator should never be allowed. In a semantic model of math, that makes sense. But mathlive is syntactic, so I don't favor that notion.

When I wrote the Mathematica editor, I think I had model for clicking that looked at the distance to nearby boxes and choose the one whose edge was closest (it might have had a few special cases). If you used something similar, there is no need to add a margin for clicking and I think would improve clicking behavior. E.g,  in the following
![image](https://user-images.githubusercontent.com/1545836/36865576-bd3b3590-1d44-11e8-83e1-4f2c333f188f.png)
if you click anywhere in the numerator except over the `x` in the numerator, the selection falls before or after the fraction.

Apologies if I am misunderstanding what the issue is.

**Comment by arnog** [comment]
I think the fundamental problem is that an empty box has a width of 0. Therefore, it cannot be selected.
I have changed the way placeholder works by making them less conspicuous. They could further be de-emphasized by being just a transparent box, but have a look at what's currently checked in and let me know what you think.

**Comment by arnog** [comment]
Placeholders are no longer inserted automatically during editing. They are only added when a new fragment is inserted. Empty denominators/numerators can now be selected.
