### ISSUE TITLE
Latex of Space in text tag 

### ISSUE THREAD

**Issue by michelmar** [arnog/mathlive#735]
Why is space replaced by '^^20' insted of ' \ ' in the latex ?
![Captura de tela 2020-12-01 032911](https://user-images.githubusercontent.com/60835138/100706344-9cd8fd80-3387-11eb-976e-6f90fc97c1c6.png)

**Comment by arnog** [comment]
Why? Because there was a bug.
I don't think it's happening in the main branch, though.

**Comment by amad-person** [comment]
Hi @arnog, may I know how to fix this bug? 

I'm using the npm release of mathlive (`v0.59`) in an Angular 11 project (browser: Firefox, OS: macOS). 

I need to create an SVG of the LaTeX returned by a mathfield. I'm using `getValue('latex-expanded')` to get the LaTeX string. Because the space character is being rendered as `^^20` by the mathfield, the generated SVG also includes `^^20` instead of a whitespace. 

I tried to sanitize the LaTeX string by:
1. replacing "^^20" with " "
2. parsing the string as Unicode

but none of these approaches worked. 

Any help would be appreciated. Thanks a lot!

**Comment by arnog** [comment]
@amad-person I believe this bug is fixed in the main branch, so you could update to that.

Otherwise, replacing "^^20" with " " should work, but it's hard for me to help as I don't know what you mean when you say it hasn't worked for you. What happens when you try to replace "^^20" with " "? Is it not replaced? Is it replaced by something else? What are you getting and how is it different from what you were expecting? Do you have some code I could look at?

**Comment by amad-person** [comment]
Thanks @arnog. I actually managed to replace the characters successfully with the regexp `/\^\^20/gm`. Sorry for the confusion!
