### ISSUE TITLE
Wrong latex output for some cases

### ISSUE THREAD

**Issue by alexprey** [arnog/mathlive#780]
## Description

`/differentialD`, `/exponentialE`, `\rd` produced by `dx`, `ee` and from keyboards, but actually that is not correct latex output. As a workaround we just replace that on `\, \mathrd{d}`, `\mathrd{e}` and that works for us, but if I copy output from editor and paste somewhere I have the correct latex output w/o any code changes. So, that looks like that output function miss step for convertion.

You can check our workaround for now, but I think that is not clear solution (https://github.com/alexprey/mathlive/commit/45edf6de916e672c627f028dbf397a62d23f2100).

It's a good if you can describe this logic in details and we can spent some time to fix that 

## Steps to Reproduce

1. Use mathlive editor
2. Put from keyboard D or d/dx from integral extended keys
3. Check latex output

### Actual Behavior

Actually that produced the wrong latex

### Expected Behavior

Must produce the valid latex output, mathml also should be supported

### Environment

**Operating System**
[macOS, Windows, iOS. Include the version if possible]

**Browser** [Safari, Chrome, IE, Firefox, etc...]

**Comment by arnog** [comment]
The issue is one of interoperability vs. abstract representation. Some of those Latex commands are indeed not broadly supported and specific Latex libraries.

I think the proper way to deal with this would be to "demote" some of those commands (`\differentialD`, `\rd`, `\exponentialE`, etc...) from built-in Latex commands to default macros. The benefit of using a macro is that internally you could continue to use `\rd` for example, but you could choose wether to get a Latex representation that uses those macros, or one that expand the macro definition depending on the situation by using `getValue('latex-expanded')`.

Note that when copying to the clipboard, the format used is already 'latex-expanded' to maximize interoperability.

**Comment by arnog** [comment]
Hmm... I just checked, and `\differentialD`, `\exponentialE` are actually already macros.

So, I'm not sure if I understand what the issue is. Is there an issue? Or is it that you just need to use `getValue('latex-expanded')` to get what you want?

**Comment by arnog** [comment]
There is now a hook [`onExport`](https://cortexjs.io/docs/mathlive/#(%22options%22%3Amodule).(MathfieldHooks%3Ainterface).onExport) that allows you to customize the clipboard export. I still don't quite understand what problem you were having since the `latex-expanded` format should have taken care of the issues you describe, but in case this is useful, I would suggest using `onExport`.
