### ISSUE TITLE
deprecation warnings: missing alternatives?

### ISSUE THREAD

**Issue by zoranpopovic** [arnog/mathlive#784]
For a few deprecation notices, it is not clear what should be used instead.  Here are the 2 that I've come across:
 - `Function "export default renderMathInElement" is deprecated` is there an alternative way to pass an element that becomes a mathlive expression?  when using templates in vue, it's a normal thing to to, it seems that matlive's own vue component is using it.  couldn't find any alernative in the docs.
 - when using getValue("json") we get: `deprecated format. Use MathJSON`  Not sure how to use MathJSON?  I saw some discussion on moving it outside of Mathlive but afaik there is no alternative to use just yet.

Any suggestions?

**Comment by arnog** [comment]
The deprecation message may not be very clear. It's the usage of `renderMathInElement` as a default export which is deprecated, you should instead import the specific function. So instead of 

```
import Mathlive from 'mathlive';
Mathlive.renderMathInElement(...)
```
use
```
import renderMathInElement from 'mathlive';
renderMathInElement`
```

For MathJson it's a bit more complicated: a new format selector (`mathJson`) will be introduced soon, however the format will be different, hence the warning.

**Comment by arnog** [comment]
The new `math-json` format is now available in the main branch.
