### ISSUE TITLE
Virtual keyboard: extended keys remain open if release mouse click outside the original key

### ISSUE THREAD

**Issue by stylebc** [arnog/mathlive#794]
## Description

When holding a key on a virtual keyboard for a while (e.g. Integral key) 
![image](https://user-images.githubusercontent.com/7346159/104555599-323a0380-564f-11eb-8484-4dfc906afe17.png)
popup with extended keys is shown, so if you release the mouse click outside the original key and outside the popup, the popup rimed opened.
Gif:
![keyboard_issue](https://user-images.githubusercontent.com/7346159/104555421-e2f3d300-564e-11eb-972f-8488cb520da0.gif)

## Steps to Reproduce

1. open the virtual keyboard on the basic example page
2. click and hold the mouse button on the integral key ![image](https://user-images.githubusercontent.com/7346159/104555599-323a0380-564f-11eb-8484-4dfc906afe17.png)
3. release the mouse button outside the integral key, for example on the minus key.
### Actual Behavior

popup with integrals remain opened

### Expected Behavior

popup with integrals closes

### Environment

Chrome

**Comment by wazelin** [comment]
The behavior is the same for me on macOS 11.1 under Chrome 88.0.4324.96 (Official Build) (x86_64).

In addition, I should also probably mention the fact it's not registering a click on a key if the pointer is at the very bottom of it, due to the key popping up a bit on `mousedown`.
![ezgif-7-0a5dafb9760c](https://user-images.githubusercontent.com/2943256/105835221-d31fab80-5fcb-11eb-90e4-5d9fa3ba9e7a.gif)

**Comment by arnog** [comment]
Fixed in mathlive@0.62.0
