### ISSUE TITLE
Virtual Keyboard as permanent keyboard + accessibility?

### ISSUE THREAD

**Issue by oatymart** [arnog/mathlive#800]
A few questions about virtual keyboard use. I gather that the feature is mainly intended to help with input on mobile devices, but I'm wondering if it can be adapted to be accessible for all users.

1. None of the keyboard controls are keyboard-focusable. I would like to be able to:
  - A) focus and trigger all the keyboard buttons as the main mode of input (since users may not be aware of the different commands available when typing directly into the mathfield). Apart from adding tabindexes and keyup listeners, the main problem I see here is tab order, since the virtual keyboard is injected at the end of the document and it's not very practical to navigate quickly between mathfield and kb. Is it something you have ideas about or would consider?
  - B) focus and trigger the keyboard toggle button by keyboard (might not be needed, see next point)

2. In my use case the mathfield will be part of a dedicated modal overlay. Would you consider:
  - A) adding a `virtualKeyboardMode: "on"` mode to make the keyboard permanently displayed? (Currently I have used `"onfocus"` mode and overridden the visibility, opacity and transition properties using CSS to achieve something similar.)
  - B) allowing to inject the virtual keyboard element into any specified container? (That may be asking too much, but it could be the logical next step if the permanent mode and accessible keys are feasible.)

**Comment by gmacciocca** [comment]
I second all the requests above, with particular emphasis on being able to have the keyboard always "on" (virtualKeyboardMode), and rendering the keyboard within a given parent element, to control its positioning in the viewport.

The other accessibilities request made by @oatymart are also basic requirements for all modern websites.

**Comment by arnog** [comment]
Great questions!

The virtual keyboard is intended to be useful both on mobile and desktop: it's really *required* on mobile, and *useful* on desktop.

A lot of thought has been put into making the mathfield accessible and it has been tested with users using screen readers rather than just following generic "accessibility guidelines". The feedback I got from users using screen readers is that they were not very interested in having the virtual keyboard be keyboard navigable: it did not seem to make sense to them to have to navigate the virtual keyboard by pressing the tab key repeatedly when they could just type the equivalent command (using the latex mode, for example), faster. Maybe your users feel differently, I dunno.

1A/ With the exception of the caveat above, seems like that would be feasible. Note that the items in the "toolbar" of the virtual keyboard would also need to be navigable (so you can switch between multiple keyboard layouts).

1B/ There is already a keyboard shortcut to toggle the virtual keyboard: alt/option + Space. Presumably this keyboard shortcut could also focus the virtual keyboard if it was focusable. That seems more useful than making the virtual keyboard toggle widget focusable, then having to navigate to the virtual keyboard.

2A/ I think `"onfocus"` is sufficient: if the virtual keyboard is focused, it should consider the mathfield itself as focused (think of the virtual keyboard as a "sub-element" of the mathfield). On the other hand if a plain text field is focused, the virtual keyboard should not be displayed, since interacting with it will not actually send input to the focused text field. 

This is something that is not very hard to implement using the `MathfieldElement` interface (it's much harder/impossible without using the custom element: a custom element can be focused *and* have a sub-element focused, i.e. there are two focus trees when using a custom element).

2B/ yes, having an option to specify the parent element of the virtual keyboard makes sense. 

I believe the logic in `toggleVirtualKeyboard()` would have to be updated. Having a quick glance at the code right now seems that there appears to be a problem in the logic as it is: a new keyboard is created even if another mathfield previously inserted one in the page. That doesn't seem right. 

Also, the handling of the alternate keys panel (the panel that shows up when you press and hold a key) would have to be updated so that this panel is also attached to a parent container of your choice (see `showAlternateKeys()` and `getSharedElement()`). Also care would have to be taken to ensure that shared virtual keyboard (i.e. the `use-shared-virtual-keyboard` attribute) still works, specifically the examples in `examples/iframe`.

**Comment by oatymart** [comment]
Thanks for the quick reply on this. I was able to work around my issues 2A and 2B for now, using some CSS. But would be interested in trying to implement those features in Mathlive in the near future, if there is a demand for it.

For 1A and 1B my needs changed and I can live without it for now. But it would be a nice improvement if you intend to reach the next level in accessibility.

**Comment by arnog** [comment]
Great! Let me know if you start working on (2A) or (2B): I'd be happy to guide you if needed and review/merge a PR when you have one.

For (1A) and (1B), I'd also be happy to consider a PR, but I would like for it to include some feedback from users using screen readers that this is something actually useful to them (the feedback I have gotten so far is that it is not). I'd hate for anyone to spend time working on improving accessibility by implementing features that are actually not useful to those users who would use them.

**Comment by arnog** [comment]
(2B) has been implemented with PR#905 as the `virtualKeyboardContainer` option.

Let me know if you're still interested in (1A) or (1B) and we can discuss how to proceed.

In the meantime, I'm going to close this as resolved.

**Comment by Luisito3107** [comment]
I am creating a MathLive+MathJax plugin as an equation editor plugin for TinyMCE, but as MathLive needs to be contained in the TinyMCE dialog iframe, the onfocus glitches a lot (specially on key longpress), so I think an `virtualKeyboardMode: "on"` option would be really useful!

![image](https://user-images.githubusercontent.com/22570099/116122872-eeac5800-a687-11eb-9fe1-8d0dbd67571e.png)

**Comment by arnog** [comment]
@Luisito3107 Which version of Mathlive are you using? Are you using the `virtualKeyboardContainer` option? Can you describe what you mean by "glitches a lot"?

**Comment by Luisito3107** [comment]
I am using the version provided by the CDN (https://unpkg.com/mathlive/dist/mathlive.min.js).
I am setting up the MathLive only with 
`{
    smartMode: true,
    virtualKeyboardMode: 'onfocus',
    virtualKeyboardTheme: 'apple'
}`
Only the first long press works fine when within an iFrame, then the keyboard closes but the key popup it's still there and it's really difficult to use the key holding options. After changing the virtualKeyboardMode to onfocus (from manual), the keyboard opens itself again after that.
![image](https://user-images.githubusercontent.com/22570099/116139791-07266d80-a69c-11eb-9d3b-fc68470461b2.png)

That problem does not occur in the desktop version of Chrome, so maybe is a problem of Chrome for Android and a workaround may be the option to always keep visible the virtual keyboard :)

**Comment by arnog** [comment]
The handling of the virtual keyboard in iframes has been improved in the main  branch and `virtualKeyboardContainer` can now display the virtual keyboard within.

**Comment by arnog** [comment]
The handling of the virtual keyboard in iframes has been improved in the main  branch and `virtualKeyboardContainer` can now display the virtual keyboard within.

**Comment by eokwukwe** [comment]
@Luisito3107 would you mind sharing your implementation for the Mathlive equation plugin for TinyMCE editor?

**Comment by Luisito3107** [comment]
> @Luisito3107 would you mind sharing your implementation for the Mathlive equation plugin for TinyMCE editor?

Sorry, I had to put this project aside a few years ago because of college. I revisited the files a couple months ago and I'm pretty sure this TinyMCE implementation I created doesn't work anymore, don't know if it is because of MathLive or TinyMCE changes over the years. As far as I remember, only MathLive was from CDN, TinyMCE was self-hosted.
I'll try to find the files, I'll share them if I find them.
