### ISSUE TITLE
\frac command throws error

### ISSUE THREAD

**Issue by oatymart** [arnog/mathlive#806]
On https://mathlive.io/examples/basic/index.esm.html, it's not possible to execute the `\frac` command in the mathfield, and there's a console error as soon as you type even `\f`.

The error seems to come from the `updateDimensions()` function.

Chrome 87 and Firefox 85 on Mac

![Screenshot 2021-01-29 at 11 01 19](https://user-images.githubusercontent.com/43652944/106260978-54bc4700-6221-11eb-9d41-b68679e078ed.png)

**Comment by arnog** [comment]
This bug has been fixed in the main branch.

**Comment by PhilippImhof** [comment]
I have just come across this. When I press `Shift+Alt+7` on a Mac, there is a `/` instead of a `\` in the text field.
![image](https://user-images.githubusercontent.com/52650214/106380647-fd021500-63b3-11eb-8c53-4e371175689a.png)


If I copy a backslash and paste it into the text field and add, for example `sin` to it, this is not treated as `\sin`: 

![image](https://user-images.githubusercontent.com/52650214/106380644-f4114380-63b3-11eb-9fab-09556f19229e.png)

**Comment by arnog** [comment]
@PhilippImhof I am not sure that I follow what you are reporting and whether it's related to the original report:
- which version of Mathlive did you use?
- what keyboard layout/locale are you using (I would not expect `shift+option+7` to produce either a "/" or a "\" on a QWERTY keyboard)

**Comment by PhilippImhof** [comment]
I was using `v0.59.0-93-g1b6a4ee-dirty` on [the examples page](http://mathlive.io/examples/basic/index.esm.html)

It happens using a QWERTZ keyboard (but also when switching to QWERTY) with de-CH locale. On a Mac `shift+option+7` normally produces `\`, AFAIK also for English locales.

It is only partially related to the report above, because it is not the same error, but also an error when trying to type `\frac`.

**Comment by arnog** [comment]
OK, got it. So this is a problem un-related to this report. As I mention above, the problem originally reported here is fixed in the main branch. The problem you are reporting, however, is not. This is an issue specific to the QWERTZ keyboard: specifically, there is a keyboard shortcut defined that maps "option + /" to a literal forward slash character (i.e. `\/`). However, since on the QWERTZ keyboard the only way to produce the backslash character is by pressing the option key (with shift + 7), it is no longer possible to produce the backslash character. The solution is probably to disable this keyboard shortcut.

Would you mind opening a new issue to track this?

**Comment by PhilippImhof** [comment]
I will do so, yes.

**Comment by arnog** [comment]
Fixed in mathlive@0.60.0
