### ISSUE TITLE
Eliminate  '.' in speech text

### ISSUE THREAD

**Issue by NSoiffer** [arnog/mathlive#84]
## Description
I believe '.' and ',' were added to speech strings to cause the speech engine to add a little pause at that point. SSML is now being used, so the punctuation is not really appropriate as the times in the `break` are more precise. Furthermore, sometimes the speech engine will speak the `.`, which is bad.

An example where that happens is when a common fraction is spoken:
```
five eights <mark name="83earh"/> . <break time="150ms"/>
```
Perhaps because the `.` is along between two tags, it gets spoken by aws polly as "dot".

I suggest that all punctuation should be deleted. If SSML is not being used, then longer breaks should be converted to `.` and shorter ones to `,`. That would be an easy thing to do in the code.

**Comment by arnog** [comment]
I believe you're correct that the dot is voiced when it is in between two tags, or not clearly the end of a sentence (i.e. with a space before it instead of a word).
That said, a "." serves two purposes: adding a pause, but it also changes the intonation of the utterance, using a falling intonation. All the dots having to do with a pause should be removed and replaced with an appropriate <break> tag. I'm not sure about those controlling the intonation.

**Comment by NSoiffer** [comment]
Thanks for the info -- I didn't know you were trying to achieve a fall
intonation with some of the '.'s. I'm having trouble figuring out when they
would be appropriate. Did you have some internal decision process that
would lead you to adding one?

    Neil
