### ISSUE TITLE
Inserting space code (for example "\\;") transforms fractions display from math to text

### ISSUE THREAD

**Issue by evyatarbh** [arnog/mathlive#886]
## Description
We are using MathLive as formulas text-area and we need some spacing between certain words/elements.
However, once a formula includes a whitespace code some of the math display breaks (specifically fractions displayed vertically).
We convert the formula to ASCIIMath and insert it back in math mode.
Fractions are in the following syntax - 
(1)/(2)
When a whitespace char is included in the inserted text it would displayed as the above text, while without it a vertical fraction would be displayed (as expected).

## Steps to Reproduce
mathField.insert('(1)/(2)\\\\;', {
      mode: 'math'
    });

Try running the above command with and without the "\\\\;" part.

### Actual Behavior
Fraction is displayed as text

### Expected Behavior
Fraction is displayed vertically as math

### Environment

**Operating System**
Windows

**Browser** 
Chrome

**Comment by arnog** [comment]
The behavior you are seeing is expected.

If no `format` option is specified to the `insert()` command it tries to "guess" what format the content should be interpreted as. 

The expression "`(1)/(2)`" "looks like" MathASCII and is interpreted as such and converted to the Latex "`\frac{1}{2}`".

However, the expression "`(1)/(2)\\;`" "looks like" Latex, because it includes a Latex command (indicated by the backslash character). Therefore, it is interpreted as the literal Latex expression and the fraction is not converted.

Unfortunately, MathASCII does not support spacing commands, so if you need to insert spacing commands, you need to use Latex as the format of the content you insert. Alternatively, you could call `insert()` twice, once with the MathASCII content, and then with the Latex spacing commands you want.

As a side note, the `mode` option is "`math`" by default, so you don't need to specify it in this case. The default `format` option is `auto`, but you can specify it explicitly if you know what format the content is in (for example `latex` or `ASCIIMath`) to avoid "guessing" wrong.

**Comment by evyatarbh** [comment]
@arnog I understand and will try to convert the content back to "frac" syntax. Thanks.
