### ISSUE TITLE
Feature: provide recommended templates to reproduce bugs / issues

### ISSUE THREAD

**Issue by mindreframer** [arnog/mathlive#904]
## Description

As suggested in https://github.com/arnog/mathlive/issues/902 to improve the process of getting reproducible bugs / issues reported by users of Mathlive, it would be great to provide them consistent working scaffold with some variations, that makes reproducing a bug much quicker. 

We have 2 options: 
- work with app generators ( like React CRA or similar) 
  - PRO: more professional, CONTRA: requires publishing to NPM, more scripts / automation / etc
- provide a simple repo, that can be forked / cloned / etc and  
  - PRO: quicker to implement, less maintenance, CONTRA: user would download all package (vue / react / etc), even when not used

### REPOs:
- https://github.com/mindreframer/mathlive-bug-issue-templates
- https://github.com/mindreframer/mathlive-create-app

The code in repos is an adjusted copy from https://github.com/vitejs/vite/tree/main/packages/create-app. 
Why? Because using Vite.js makes coding in the browser so much more nicer, with very quick boot times and very fast real-time browser refreshing. 

Really hope you would consider implementing it as recommendation for bug reports.

Cheers!

**Comment by mindreframer** [comment]
@arnog Now it includes a ready Jest config (+ esbuild-jest for extra boost) + basic test file per template to simplify providing real test cases with Jest. Plus CI configuration that runs all tests for all templates.

**Comment by arnog** [comment]
Good idea.

I've added a link to those projects in the bug template.

I would suggest making a few changes to the projects, though. I do not recommend modifying/injecting a stylesheet inside the shadow DOM. There are alternative methods for the three examples you use: (1) style the element itself, not the `.ML__fieldcontainer`, (2) specify a `--highlight` or `--hue` CSS variable in your document rather than overriding the `. ML__selection` selector (CSS variables are passed through the shadow DOM) and the (3) does nothing.

See https://cortexjs.io/mathlive/guides/customizing/ for more info on customizing a mathfield.

**Comment by mindreframer** [comment]
@arnog Alright! Removed the injected stylesheet - https://github.com/mindreframer/mathlive-bug-issue-templates/pull/2/files + modified styles via recommended ways. 

I was kinda hoping that those projects might live in a more official place, like the `cortex-js` Github organization. But I'm also fine maintaining it under my private account. 

Currently I'm leaning more into the just using Github and cloning / forking the repo, this keeps things simpler in terms of tooling and agility.

**Comment by mindreframer** [comment]
@arnog since the Github issues template is now adjusted, I'm going to close this issue. Thanks!
