### ISSUE TITLE
[Feature Request] Add option to revert to command mode

### ISSUE THREAD

**Issue by tjquillan** [arnog/mathlive#915]
## Edit
I have since learned (https://github.com/arnog/mathlive/issues/915#issuecomment-826382433) that this is intended and is due to the new Latex Mode feature. However it would then be nice to have an option to revert to command mode or disable it completely. This is because in my app pressing enter is regarded as submission making leaving Latex Mode once entered difficult.

## Description
When typing the latex for a latex symbol ie. `\neg`, `\cup`, or others tab completion of these symbols does not appear to work anymore.

**Codesandbox:**
https://codesandbox.io/s/brave-lewin-5hvg2?file=/index.html

## Steps to Reproduce

1. Open the above Codesandbox
2. Attempt to type a latex symbox ie. `\cap`
3. Attempt to complete the symbol using tab
### Actual Behavior

When pressing tab nothing happens and it appears to stay in its latex symbol completion state.

### Expected Behavior

The symbol is substituted in and normal typing can be proceeded.

This regression began with `0.60.0` as going to `0.59.0` produces the expected functionality.

### Environment

**MathLive version**
`0.63.0` however issue began in `0.60.0`

**Operating System**
Arch Linux

**Browser**
Firefox

**Comment by arnog** [comment]
I tried with the code sandbox. Here's what I see:
- I type "\ca"
  - I see a proposed completion of `\cap` (the "p" is greyed out)
- I press TAB
  - The cursor moves after the "p" and the p is no longer greyed out
- I press return
  - The "\cap" command is inserted in the mathfield

That's the expected behavior. Do you see something different?

Note that the behavior of the Latex mode has changed from the previous Command mode in 0.60. Here's an extract from the Changelog:

## New **Latex Mode**

This mode replaces the previous **Command Mode**. While the **Command Mode**  (triggered by pressing the **\\** or **ESC** key) was only intended to insert  a single Latex command (e.g. "\aleph"), the **Latex Mode** is a more  comprehensive Latex editing mode.

To enter the **Latex Mode**, press the **ESC** key or the **\\** key. While in  this mode, a complex Latex expression can be edited. Press the **ESC** or  **Return** key to return to regular editing mode.

To quickly peek at the Latex code of an expression, select it, then press  **ESC**. Press **ESC** again to return to the regular editing mode.

To insert a command, press the **\\** key, followed by the command name. Press  the **TAB** key to accept a suggestion, then the **RETURN** key to return to  regular editing mode (previously pressing the **TAB** key would have exited  the command mode).

**Comment by iboyperson** [comment]
Ah I am sorry about that, I hadn't noticed that in the changelog. I will rename this issue as a feature request for an option to use the previous behavior or disable latex mode. Alternatively, I can create a new issue if you would prefer me to close this and make a new one. For context the app I am building would treat pressing enter as submission. So upon entering latex mode the user would have difficulty escaping it.

**Comment by iboyperson** [comment]
Updated the issue description to explain my mistake and make it into more of a feature request.

**Comment by stefnotch** [comment]
> This is because in my app pressing enter is regarded as submission making leaving Latex Mode once entered difficult.

Would it be possible for you to use the `onCommit` hook?

**Comment by tjquillan** [comment]
Yes, that did work (see: https://github.com/tjquillan/discrete-calculator/blob/c2f7b912af153eff06ce534c7f82841453aed3ea/src/components/Mathfield/Mathfield.tsx#L73) alternatively I was using this (https://github.com/tjquillan/discrete-calculator/blob/223b979dce7ecb1674c59324fdf2be5ef91ed5a1/src/components/Mathfield/Mathfield.tsx#L79) as a workaround before, but that is much cleaner. Thanks for the tip!

**Comment by stefnotch** [comment]
@tjquillan Sweet, glad that I managed to help. The discrete calculator site also looks really neat, I really like it 😄 

I also built a [truth table tool](https://tuwien2020.github.io/tgi-pages/#/truth-table?input=a+and+(b+xor+1+nand+!a)+=%3E+c) in the past, but that one doesn't use mathlive. Thus, it's not quite that cool. If you want to take code or inspiration from there, feel free to. It's [open source](https://github.com/tuwien2020/tgi-pages) after all.

My personal little suggestions/ideas would be
- a tiny bit of documentation somewhere on the page doesn't hurt, even just two or 3 examples can go a long way
- you can put the string into the URL, making it super easy to share
- you can use the [shiny new MathJson](https://github.com/arnog/mathlive/blob/master/CHANGELOG.md#0680-2021-05-31), which should spare you the trouble of having to parse LaTeX
