### ISSUE TITLE
Missing plonk and moveOutOf in fractions

### ISSUE THREAD

**Issue by stefnotch** [arnog/mathlive#955]
## Description

When the caret is at the top of a fraction and you press up, no "plonk" sound gets triggered

![image](https://user-images.githubusercontent.com/10220080/119973488-d778c700-bfb3-11eb-983e-6c404719043b.png)

(Beautiful arrow added using paint)

## Steps to Reproduce

1. Go to https://cortexjs.io/mathlive/
2. Put the caret at the top of the fraction
3. Press the `up` arrow key

### Actual Behavior

Nothing happens

### Expected Behavior

I expected a plonk sound and a `moveOutOf` event

### Environment

**MathLive version** v0.67.0

**Operating System** Windows 10

**Browser** Firefox 88 and Microsoft Edge

**Comment by arnog** [comment]
Good catch. I think the `plonk` would make sense in that case, but I don't think you could have both a `plonk` **and** a `moveOutOf`. It would seem a bit weird that while inside the equation you could "leave it"...

**Comment by stefnotch** [comment]
@arnog There is already a plonk and/or a `moveOutOf` at the end of the equation. 

Regarding as to why I'd love a `moveOutOf` to get triggered there is because I happen to be working with an editor where multiple equations are below each other. To quickly jump from one equation to the next, you simply hit the up or down key a few times.

Desmos also does it like that:

![image](https://user-images.githubusercontent.com/10220080/120008029-d8711f00-bfda-11eb-8d73-2ba6a3fbb93c.png)

**Comment by arnog** [comment]
Right, I was thinking that the `mouveOutOf` hook at the top level of the equation made sense, but not "inside", but you've convinced me, that does feel like that could work. So, call the `moveOutOf` hook to (potentially) shift the focus to something else, and if not handled, `plonk`.

**Comment by arnog** [comment]
OK, looking into this, it's a  bit more complicated than I thought.

Currently, there are two hooks, `tabOutOf` and `moveOutOf`. They both map to a single `focus-out` event, which is dispatched when using the `<math-field>` element. `tabOutOf` is triggered by the **tab** key, while `moveOutOf` is triggered with the **arrow** keys. The documentation (I wrote) is a bit confusing, because it seems to imply that in both cases the focus would change to the next/previous tabable element if the event was not canceled (or the hook returned **false**), but that's not what's actually happening. It does happen when using **tab**, but not the **arrow** keys.

Furthermore, it turns out that tabbing to the next/previous element is non-trivial. There is already some logic to handle it when pushing the **tab**key, but if you wanted that behavior from the **arrow** keys, I would need to add a mathfield API to do that explicitly.

Or perhaps I can change the behavior so that going `upward` or `backward` with the **arrow** keys or with **shift+tab** would go to the previous tabable element by default, and `forward` or `downward` with the **arrow** keys or with **tab** would go to the next tabable element.

Then you could always intercept the `focus-out` event to do something different (or the `mouveOutOf` hook, but really the `focus-out` event is the "modern" way of doing it).

Hmmm....

**Comment by stefnotch** [comment]
> because it seems to imply that in both cases the focus would change to the next/previous tabable element if the event was not canceled (or the hook returned false), but that's not what's actually happening. It does happen when using tab, but not the arrow keys.

Sounds like the correct behavior to me. There is a well defined tabbing order, but arrow keys frequently (?) do their own thing. 
Moving to the next element when pressing the arrow keys seems like something that could be left to the user.

**Comment by arnog** [comment]
Yeah, that makes sense. Same thing with a regular textfield: tab changes focus, but arrow keys don't.

I'm going to add a `move-out` event that will be triggered only by the **arrow** keys and keep the `focus-out` for the **tab** key. The `move-out` event will `plonk` by default if not handled.

Would you find it useful to have a way to "tab to the next focusable element" or can you already easily figure that out in your `move-out` handler?

**Comment by stefnotch** [comment]
Sounds great :)
I can already easily figure out how to get the next interesting element.


By the way, would it be useful to add those custom events to the Typescript types for the `MathfieldElement`? Currently it's a bit hard to discover them:

![image](https://user-images.githubusercontent.com/10220080/120018526-93071e80-bfe7-11eb-8ccf-91240de446d5.png)

In case you do want them to show up when typing `addEventListener`, adding something like this to `mathfield-element.d.ts` should work
```ts
addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: MathfieldElement, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: MathfieldElement, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
```

**Comment by arnog** [comment]
Great point! Done.
